/*****************************************************************************
 * (C) Copyright 2000-2009, Wintegra. All rights reserved.
 * WINTEGRA CONFIDENTIAL PROPRIETARY
 * Contains Confidential Proprietary information of Wintegra.
 * Reverse engineering is prohibited.
 * The copyright notice does not imply publication.
 ****************************************************************************/

/*****************************************************************************
 *
 * File: wpx_serdes.c
 *
 *****************************************************************************/
#include <stdio.h>
#include <string.h>

#ifndef WP_TYPES_H
#include "api/wp_types.h"
#endif
#ifndef WPI_HW_H
#include <include/core/hardware/wpi_hw.h>
#endif
#ifndef WPX_BOARD_IF_H
#include "../board/wpx_board_if.h"
#endif

#include "wpx_serdes.h"
#include "wpx_board_data.h"

static void WPX_SerdesInit_1_G_SingleLane(wpx_serdes *serdes_regs, WP_U32 serdes, WP_U8 loopback_mode);
static void WPX_SerdesInit_2_5_G_SingleLane(wpx_serdes *serdes_regs, WP_U32 serdes, WP_U8 loopback_mode);
static void WPX_SerdesInit_1_G_QuadLane(wpx_serdes *serdes_regs, WP_U32 serdes, WP_U8 loopback_mode);
static void WPX_SerdesInit_2_5_G_QuadLane(wpx_serdes *serdes_regs, WP_U32 serdes, WP_U8 loopback_mode, WP_U32 isXgi);
static void WPX_SerdesLockEnBlockDisable(WP_U32 *quad_io_ctrl_value,
                                         WP_U32 *quad_io_ctrl_value_loopback_nes);

extern wpx_board_configuration current_configuration;

wpx_port_to_serdes_connection port_to_serdes[WPX_CONFIGURE_MAX_CONFIGURATIONS] =
{
   {
      /*WPX_CONFIGURE_DEFAULT_CHECKIN*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES3, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET4 */  WPX_SERDES3, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET6 */  WPX_SERDES3, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /*WPX_CONFIGURE_CHECKIN_TDI_16*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES3, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET4 */  WPX_SERDES3, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET6 */  WPX_SERDES3, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /*WPX_CONFIGURE_UFE_UPI2_TDM*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET4 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET8 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET14 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET15 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET16 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI1 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /* WPX_CONFIGURE_TDI_16_UPI1*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET4 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET8 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET14 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET15 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET16 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI1 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /* WPX_CONFIGURE_2UPI_2XGI_6SGMII2G*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET4 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET8 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET9 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET14 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET16 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES3, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
      }
   },
   {
      /*WPX_CONFIGURE_1UPI_1XGI_4GMII_8SGMII*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET4 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET6 */  WPX_SERDES3, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /*WPX_CONFIGURE_1XGI_6RGMII_6SGMII*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET4 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /*WPX_CONFIGURE_1UPI_1XGI_6RTBI_6SGMII*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET4 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /*WPX_CONFIGURE_1XGI_6SMII_6SGMII*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES3, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET4 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /*WPX_CONFIGURE_2RMII_8TDI_1XGI_10SGMII*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES3, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET4 */  WPX_SERDES3, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET6 */  WPX_SERDES3, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /* WPX_CONFIGURE_8TDI_1UPI_1XGI_10SGMII */
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES3, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET4 */  WPX_SERDES3, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET6 */  WPX_SERDES3, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /*WPX_CONFIGURE_2UPI_1XGI_10SGMII*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES3, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET4 */  WPX_SERDES3, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET6 */  WPX_SERDES3, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /*WPX_CONFIGURE_2UPI_1XGI_10SGMII_UFE4*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES3, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET4 */  WPX_SERDES3, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET6 */  WPX_SERDES3, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /*WPX_CONFIGURE_2UPI_16bit_1XGI_10SGMII*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES3, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET4 */  WPX_SERDES3, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET6 */  WPX_SERDES3, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /* WPX_CONFIGURE_BRG_MUX*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET4 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET8 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET14 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET15 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET16 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI1 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /* WPX_CONFIGURE_PPS_FCLK_SELECT*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET4 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET8 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET14 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET15 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET16 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI1 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /* WPX_CONFIGURE_SMA_DIRECTION*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET4 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET8 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET14 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET15 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET16 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI1 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /* WPX_CONFIGURE_2SGMII_2SGMII2G_16TDI*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET4 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET14 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET15 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET16 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI1 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /*WPX_CONFIGURE_2UPI_1XGI_10SGMII_UPI_CLK_100M*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES3, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET4 */  WPX_SERDES3, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET6 */  WPX_SERDES3, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /* WPX_CONFIGURE_6SGMII_1SGMII2G_2SMII*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET4 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
       { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   },
   {
      /* WPX_CONFIGURE_2UPI_L3_2XGI_6SGMII*/
      {
         { /*WP_PORT_ENET1 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET4 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES3, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
      }
   },
   {
      /* WPX_CONFIGURE_UPI1_TDI8_16_10SGMII */
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES3, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET4 */  WPX_SERDES3, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET6 */  WPX_SERDES3, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
   }
   },
   
   {
      /* WPX_CONFIGURE_2XGI_6SGMII*/
      {
         { /*WP_PORT_ENET1 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET4 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES3, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
      }
   },   
   {
      /* WPX_CONFIGURE_2UPI_2XGI_6SGMII2G_UFE448*/
      {
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET4 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET5 */  WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET6 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET8 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET9 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET14 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_2_5G},
         { /*WP_PORT_ENET16 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES3, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
      }
   },
   {
      {
         /* WPX_CONFIGURE_UPI3_UFE412*/
         { /*WP_PORT_ENET1 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET2 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET3 */  WPX_SERDES3, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET4 */  WPX_SERDES3, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET5 */  WPX_SERDES3, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET6 */  WPX_SERDES3, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_ENET7 */  WPX_SERDES1, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET8 */  WPX_SERDES0, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET9 */  WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET10 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET11 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET12 */ WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
         { /*WP_PORT_ENET13 */ WPX_SERDES4, WPX_SERDES_LANE_0, WPX_SERDES_1G},
         { /*WP_PORT_ENET14 */ WPX_SERDES4, WPX_SERDES_LANE_1, WPX_SERDES_1G},
         { /*WP_PORT_ENET15 */ WPX_SERDES4, WPX_SERDES_LANE_2, WPX_SERDES_1G},
         { /*WP_PORT_ENET16 */ WPX_SERDES4, WPX_SERDES_LANE_3, WPX_SERDES_1G},
         { /*WP_PORT_XGI1 */   WPX_SERDES2, WPX_SERDES_LANE_ALL, WPX_SERDES_2_5G},
         { /*WP_PORT_XGI2 */   WPX_SERDES_NA, WPX_SERDES_LANE_NA, WPX_SERDES_RATE_NA},
      }
   }
};



WP_U8 serdes_loopback_mode[WPX_SERDES_NA] =
{0, 0, 0, 0, 0};


wpx_serdes_mux_ctrl serdes_mux_configurations[WPX_CONFIGURE_MAX_CONFIGURATIONS]=
{
/* WPX_CONFIGURE_DEFAULT_CHECKIN           */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 WP_PORT_ENET3
   SERDES 3 LINE 1 WP_PORT_ENET5
   SERDES 3 LINE 2 WP_PORT_ENET4
   SERDES 3 LINE 3 WP_PORT_ENET6
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x0000091b,
      0x7fff071c
   },
/* WPX_CONFIGURE_CHECKIN_TDI_16            */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 N/A
   SERDES 2 LINE 1 N/A
   SERDES 2 LINE 2 N/A
   SERDES 2 LINE 3 N/A
   SERDES 3 LINE 0 WP_PORT_ENET3
   SERDES 3 LINE 1 WP_PORT_ENET5
   SERDES 3 LINE 2 WP_PORT_ENET4
   SERDES 3 LINE 3 WP_PORT_ENET6
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x00fff91b,
      0x7fff071c
   },
/* WPX_CONFIGURE_UFE_UPI2_TDM              */
   {0},
/* WPX_CONFIGURE_TDI_16_UPI1               */
   {0},
/* WPX_CONFIGURE_2UPI_2XGI_6SGMII2G        */
/* SERDES 0 LINE 0 WP_PORT_ENET9 2,5G
   SERDES 1 LINE 0 WP_PORT_ENET7 2,5G
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 WP_PORT_XGI2
   SERDES 3 LINE 1 WP_PORT_XGI2
   SERDES 3 LINE 2 WP_PORT_XGI2
   SERDES 3 LINE 3 WP_PORT_XGI2
   SERDES 4 LINE 0 WP_PORT_ENET3 2,5G
   SERDES 4 LINE 1 WP_PORT_ENET5 2,5G
   SERDES 4 LINE 2 WP_PORT_ENET13 2,5G
   SERDES 4 LINE 3 WP_PORT_ENET15 2,5G */
   {
      0x08000249,
      0x7fff04d3
   },

/* WPX_CONFIGURE_1UPI_1XGI_4GMII_8SGMII    */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 N/A
   SERDES 3 LINE 1 WP_PORT_ENET5
   SERDES 3 LINE 2 N/A
   SERDES 3 LINE 3 WP_PORT_ENET6
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x00000f3b,
      0x7fff071c
   },

/* WPX_CONFIGURE_1XGI_6RGMII_6SGMII   */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 N/A
   SERDES 3 LINE 1 N/A
   SERDES 3 LINE 2 N/A
   SERDES 3 LINE 3 N/A
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x00000fff,
      0x7fff071c
   },
/* WPX_CONFIGURE_1UPI_1XGI_6RTBI_6SGMII    */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 N/A
   SERDES 3 LINE 1 N/A
   SERDES 3 LINE 2 N/A
   SERDES 3 LINE 3 N/A
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x00000fff,
      0x7fff071c
   },
/* WPX_CONFIGURE_1XGI_6SMII_6SGMII    */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 WP_PORT_ENET3
   SERDES 3 LINE 1 WP_PORT_ENET5
   SERDES 3 LINE 2 WP_PORT_ENET4
   SERDES 3 LINE 3 WP_PORT_ENET6
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x000009ff,
      0x7fff071c
   },
   /* WPX_CONFIGURE_2RMII_8TDI_1XGI_10SGMII   */
   /* SERDES 0 LINE 0 WP_PORT_ENET8
      SERDES 1 LINE 0 WP_PORT_ENET7
      SERDES 2 LINE 0 WP_PORT_XGI1
      SERDES 2 LINE 1 WP_PORT_XGI1
      SERDES 2 LINE 2 WP_PORT_XGI1
      SERDES 2 LINE 3 WP_PORT_XGI1
      SERDES 3 LINE 0 WP_PORT_ENET3
      SERDES 3 LINE 1 WP_PORT_ENET5
      SERDES 3 LINE 2 WP_PORT_ENET4
      SERDES 3 LINE 3 WP_PORT_ENET6
      SERDES 4 LINE 0 WP_PORT_ENET13
      SERDES 4 LINE 1 WP_PORT_ENET14
      SERDES 4 LINE 2 WP_PORT_ENET15
      SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x0000091b,
      0x7fff071c
   },
/* WPX_CONFIGURE_8TDI_1UPI_1XGI_10SGMII           */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 WP_PORT_ENET3
   SERDES 3 LINE 1 WP_PORT_ENET5
   SERDES 3 LINE 2 WP_PORT_ENET4
   SERDES 3 LINE 3 WP_PORT_ENET6
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x0000091b,
      0x7fff071c
   },
/* WPX_CONFIGURE_2UPI_1XGI_10SGMII    */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 WP_PORT_ENET3
   SERDES 3 LINE 1 WP_PORT_ENET5
   SERDES 3 LINE 2 WP_PORT_ENET4
   SERDES 3 LINE 3 WP_PORT_ENET6
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x0000091b,
      0x7fff071c
   },
/* WPX_CONFIGURE_2UPI_1XGI_10SGMII_UFE4    */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 WP_PORT_ENET3
   SERDES 3 LINE 1 WP_PORT_ENET5
   SERDES 3 LINE 2 WP_PORT_ENET4
   SERDES 3 LINE 3 WP_PORT_ENET6
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x0000091b,
      0x7fff071c
   },
/* WPX_CONFIGURE_2UPI_16bit_1XGI_10SGMII    */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 WP_PORT_ENET3
   SERDES 3 LINE 1 WP_PORT_ENET5
   SERDES 3 LINE 2 WP_PORT_ENET4
   SERDES 3 LINE 3 WP_PORT_ENET6
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x0000091b,
      0x7fff071c
   },
   /*WPX_CONFIGURE_BRG_MUX */
   {0},
   /*WPX_CONFIGURE_PPS_FCLK_SELECT */
   {0},
   /*WPX_CONFIGURE_SMA_DIRECTION */
   {0},
/* WPX_CONFIGURE_2SGMII_2SGMII2G_16TDI    */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 N/A
   SERDES 2 LINE 1 N/A
   SERDES 2 LINE 2 N/A
   SERDES 2 LINE 3 N/A
   SERDES 3 LINE 0 N/A
   SERDES 3 LINE 1 N/A
   SERDES 3 LINE 2 N/A
   SERDES 3 LINE 3 N/A
   SERDES 4 LINE 0 WP_PORT_ENET3
   SERDES 4 LINE 1 WP_PORT_ENET5
   SERDES 4 LINE 2 N/A
   SERDES 4 LINE 3 N/A */
   {
      0x00ffffff,
      0x7fff04ff
   },
/* WPX_CONFIGURE_2UPI_1XGI_10SGMII_UPI_CLK_100M    */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 WP_PORT_ENET3
   SERDES 3 LINE 1 WP_PORT_ENET5
   SERDES 3 LINE 2 WP_PORT_ENET4
   SERDES 3 LINE 3 WP_PORT_ENET6
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x0000091b,
      0x7fff071c
   },
/* WPX_CONFIGURE_6SGMII_1SGMII2G_2SMII    */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 N/A
   SERDES 2 LINE 1 N/A
   SERDES 2 LINE 2 N/A
   SERDES 2 LINE 3 N/A
   SERDES 3 LINE 0 N/A
   SERDES 3 LINE 1 WP_ENET_PORT5
   SERDES 3 LINE 2 N/A
   SERDES 3 LINE 3 N/A
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x00ffff3f,
      0x7fff071c
   },
/* WPX_CONFIGURE_2UPI_L3_2XGI_6SGMII  */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 WP_PORT_XGI2
   SERDES 3 LINE 1 WP_PORT_XGI2
   SERDES 3 LINE 2 WP_PORT_XGI2
   SERDES 3 LINE 3 WP_PORT_XGI2
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x00000249,
      0x7fff071c
   },
   /* WPX_CONFIGURE_UPI1_TDI8_16_10SGMII  */
   /* SERDES 0 LINE 0 WP_PORT_ENET8
      SERDES 1 LINE 0 WP_PORT_ENET7
      SERDES 2 LINE 0 N/A
      SERDES 2 LINE 1 N/A
      SERDES 2 LINE 2 N/A
      SERDES 2 LINE 3 N/A
      SERDES 3 LINE 0 WP_PORT_ENET3
      SERDES 3 LINE 1 WP_PORT_ENET5
      SERDES 3 LINE 2 WP_PORT_ENET4
      SERDES 3 LINE 3 WP_PORT_ENET6
      SERDES 4 LINE 0 WP_PORT_ENET13
      SERDES 4 LINE 1 WP_PORT_ENET14
      SERDES 4 LINE 2 WP_PORT_ENET15
      SERDES 4 LINE 3 WP_PORT_ENET16 */
      {
         0x00fff91b,
         0x7fff071c
      },

/* WPX_CONFIGURE_2XGI_6SGMII  */
/* SERDES 0 LINE 0 WP_PORT_ENET8  
   SERDES 1 LINE 0 WP_PORT_ENET7  
   SERDES 2 LINE 0 WP_PORT_XGI1   
   SERDES 2 LINE 1 WP_PORT_XGI1   
   SERDES 2 LINE 2 WP_PORT_XGI1   
   SERDES 2 LINE 3 WP_PORT_XGI1   
   SERDES 3 LINE 0 WP_PORT_XGI2
   SERDES 3 LINE 1 WP_PORT_XGI2
   SERDES 3 LINE 2 WP_PORT_XGI2
   SERDES 3 LINE 3 WP_PORT_XGI2
   SERDES 4 LINE 0 WP_PORT_ENET13 
   SERDES 4 LINE 1 WP_PORT_ENET14 
   SERDES 4 LINE 2 WP_PORT_ENET15 
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x00000249,
      0x7fff071c
   },
   /* WPX_CONFIGURE_2UPI_2XGI_6SGMII2G_UFE448        */
   /* SERDES 0 LINE 0 WP_PORT_ENET9 2,5G
      SERDES 1 LINE 0 WP_PORT_ENET7 2,5G
      SERDES 2 LINE 0 WP_PORT_XGI1
      SERDES 2 LINE 1 WP_PORT_XGI1
      SERDES 2 LINE 2 WP_PORT_XGI1
      SERDES 2 LINE 3 WP_PORT_XGI1
      SERDES 3 LINE 0 WP_PORT_XGI2
      SERDES 3 LINE 1 WP_PORT_XGI2
      SERDES 3 LINE 2 WP_PORT_XGI2
      SERDES 3 LINE 3 WP_PORT_XGI2
      SERDES 4 LINE 0 WP_PORT_ENET3 2,5G
      SERDES 4 LINE 1 WP_PORT_ENET5 2,5G
      SERDES 4 LINE 2 WP_PORT_ENET13 2,5G
      SERDES 4 LINE 3 WP_PORT_ENET15 2,5G */
   {
      0x08000249,
      0x7fff04d3
   },
/* WPX_CONFIGURE_UPI3_UFE412    */
/* SERDES 0 LINE 0 WP_PORT_ENET8
   SERDES 1 LINE 0 WP_PORT_ENET7
   SERDES 2 LINE 0 WP_PORT_XGI1
   SERDES 2 LINE 1 WP_PORT_XGI1
   SERDES 2 LINE 2 WP_PORT_XGI1
   SERDES 2 LINE 3 WP_PORT_XGI1
   SERDES 3 LINE 0 WP_PORT_ENET3
   SERDES 3 LINE 1 WP_PORT_ENET5
   SERDES 3 LINE 2 WP_PORT_ENET4
   SERDES 3 LINE 3 WP_PORT_ENET6
   SERDES 4 LINE 0 WP_PORT_ENET13
   SERDES 4 LINE 1 WP_PORT_ENET14
   SERDES 4 LINE 2 WP_PORT_ENET15
   SERDES 4 LINE 3 WP_PORT_ENET16 */
   {
      0x0000091b,
      0x7fff071c
   }
};

wpx_serdes *WPX_SerdesBaseGet(WP_U32 wpid)
{
   return (wpx_serdes *)(WPX_AppWpIntRegBaseGet(wpid) + WPI_SERDES_BASE);
}


WP_status WPX_SerdesSetSingleLane(WP_U32 wpid, WP_U32 serdes, WP_U32 rate, WP_U8 loopback_mode)
{
   WP_status status = WP_OK;
   wpx_serdes *serdes_regs;
   wpx_serdes_mux *mux_regs;
   WP_U32 ii;
   WP_U32 polling_result;
   volatile wpx_serdes_single_io_ctrl *single_io_control;

   if(serdes > WPX_SERDES_SINGLE_LANE_LAST)
      return WPI_ERROR(WP_ERR_SERDES_ILLEGAL);

   /**********************************************************************************
   * if this serdes uses PCIe (for Multi Winpath), do not change its configurations 
   **********************************************************************************/
   if(WPX_SerdesUsedByPCIe(wpid, serdes))
      return status;

   serdes_regs = WPX_SerdesBaseGet(wpid);
   mux_regs = &(serdes_regs->serdes_mux);

   /*init sequence*/
   if(rate == WPX_SERDES_1G)
   {
      WPX_SerdesInit_1_G_SingleLane(serdes_regs, serdes, loopback_mode);
   }
   else if(rate == WPX_SERDES_2_5G)
   {
      WPX_SerdesInit_2_5_G_SingleLane(serdes_regs, serdes, loopback_mode);
   }
   else return WPI_ERROR(WP_ERR_SERDES_RATE);

   for(ii = 0; ii<WPX_SERDES_INIT_POLLING_LOOPS; ii++)
   {
      WP_Delay(WPX_SERDES_INIT_DELAY);
      single_io_control= &(mux_regs->io_ctrl_single[serdes]);

      WPI_MEM_GET(polling_result, single_io_control->single_io_ctrl1);
      if(WPX_SERDES_SINGLE_POLLING_MASK & polling_result)
         break;
   }
   if(ii ==  WPX_SERDES_INIT_POLLING_LOOPS)
      return WPI_ERROR(WP_ERR_SERDES_INIT);

   return status;
}

WP_status WPX_SerdesSetQuadLane(WP_U32 wpid, WP_U32 serdes, WP_U32 rate, WP_U8 loopback_mode, WP_U32 isXgi)
{
    WP_status status = WP_OK;

   wpx_serdes *serdes_regs;
   wpx_serdes_quad_io_ctrl *quad_io_ctrl;
   WP_U32 ii;
   WP_U32 polling_result;
   wpx_serdes_mux *mux_regs;

   if((serdes < WPX_SERDES_QUAD_LANE_FIRST) ||
      (serdes > WPX_SERDES_QUAD_LANE_LAST))
      return WPI_ERROR(WP_ERR_SERDES_ILLEGAL);

   serdes_regs = WPX_SerdesBaseGet(wpid);
   mux_regs = &(serdes_regs->serdes_mux);
   quad_io_ctrl = &(mux_regs->io_ctrl_quad[serdes-WPX_SERDES_QUAD_LANE_FIRST]);

   /*init sequence*/
   if(rate == WPX_SERDES_1G)
   {
      WPX_SerdesInit_1_G_QuadLane(serdes_regs, serdes, loopback_mode);
   }
   else if(rate == WPX_SERDES_2_5G)
   {
      WPX_SerdesInit_2_5_G_QuadLane(serdes_regs, serdes, loopback_mode,isXgi);
   }
   else return WPI_ERROR(WP_ERR_SERDES_RATE);

   for(ii = 0; ii<WPX_SERDES_INIT_POLLING_LOOPS; ii++)
   {
      WP_Delay(WPX_SERDES_INIT_DELAY);
      WPI_MEM_GET(polling_result, quad_io_ctrl->quad_io_stat);
      if(polling_result & WPX_SERDES_QUAD_POLLING_MASK)
         break;
   }
   if(ii ==  WPX_SERDES_INIT_POLLING_LOOPS)
      return WPI_ERROR(WP_ERR_SERDES_INIT);

    return status;
}


void WPX_SerdesInit_1_G_SingleLane(wpx_serdes *serdes_regs, WP_U32 serdes, WP_U8 loopback_mode)
{
   wpx_serdes_mux *mux_regs;
   wpx_serdes_single_lane *single_lane_regs;
   wpx_serdes_single_io_ctrl *single_io_control;

   mux_regs = &(serdes_regs->serdes_mux);
   single_lane_regs = &(serdes_regs->serdes_single[serdes]);
   single_io_control = &(mux_regs->io_ctrl_single[serdes]);

   /* IO_CTRL_1,0x5001 */ WPI_MEM_SET(single_io_control->single_io_ctrl1, 0x00005001);
   /* IO_CTRL_1,0x5000 */ WPI_MEM_SET(single_io_control->single_io_ctrl1, 0x00005000);
   /* IO_CTRL_1,0x5001 */ WPI_MEM_SET(single_io_control->single_io_ctrl1, 0x00005001);
   WP_Delay(WPX_SERDES_TOGGLE_DELAY);
   /* CMU_001,  0x9641 */ WPI_MEM_SET(single_lane_regs->cmu[1], 0x9641);
   /* CMU_002,  0x2352 */ WPI_MEM_SET(single_lane_regs->cmu[2], 0x2352);
   /* CMU_003,  0xA600 */ WPI_MEM_SET(single_lane_regs->cmu[3], 0xA600);
   /* LANE_303, 0x0B0F */ WPI_MEM_SET(single_lane_regs->lane[3], 0x0B0F);
   /* GPON_601, 0x8300 */ WPI_MEM_SET(single_lane_regs->gpon[1], 0x8300);
   /* GPON_600, 0x808A */ WPI_MEM_SET(single_lane_regs->gpon[0], 0x808A);
   /* GPON_603, 0x0200 */ WPI_MEM_SET(single_lane_regs->gpon[3], 0x0200);
   /* IO_CTRL_0, 0x00000002 */ WPI_MEM_SET(single_io_control->single_io_ctrl0, 0x0001C002);
   if(loopback_mode)
   /* IO_CTRL_1, 0x00095801 */ WPI_MEM_SET(single_io_control->single_io_ctrl1, 0x00095801);
   else
   /* IO_CTRL_1, 0x00015801 */ WPI_MEM_SET(single_io_control->single_io_ctrl1, 0x00015801);
}

void WPX_SerdesInit_1_G_QuadLane(wpx_serdes *serdes_regs, WP_U32 serdes, WP_U8 loopback_mode)
{
   wpx_serdes_mux *mux_regs;
   wpx_serdes_quad_io_ctrl *quad_io_ctrl;
   WP_U32 ctrl_value = 0x05638000;
   WP_U32 ctrl_value_loopback_nes = 0x05638080;

   mux_regs = &(serdes_regs->serdes_mux);
   quad_io_ctrl = &(mux_regs->io_ctrl_quad[serdes-WPX_SERDES_QUAD_LANE_FIRST]);

   /*IO_CTRL_0, 0x00050000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl0, 0x00050000);
   /*IO_CTRL_0, 0x00040000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl0, 0x00040000);
   /*IO_CTRL_0, 0x00050000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl0, 0x00050000);
   WP_Delay(WPX_SERDES_TOGGLE_DELAY);

   /*IO_CTRL_1, 0x1600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl1, 0x01600000);
   /*IO_CTRL_2, 0x1600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl2, 0x01600000);
   /*IO_CTRL_3, 0x1600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl3, 0x01600000);
   /*IO_CTRL_4, 0x1600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl4, 0x01600000);

   if(loopback_mode & WPX_SERDES_LANE0_LOOPBACK)
   /*IO_CTRL_1, 0x5600080 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl1, ctrl_value_loopback_nes);
   else
   /*IO_CTRL_1, 0x5600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl1, ctrl_value);
   if(loopback_mode & WPX_SERDES_LANE1_LOOPBACK)
   /*IO_CTRL_2, 0x5600080 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl2, ctrl_value_loopback_nes);
   else
   /*IO_CTRL_2, 0x5600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl2, ctrl_value);
   if(loopback_mode & WPX_SERDES_LANE2_LOOPBACK)
   /*IO_CTRL_3, 0x5600080 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl3, ctrl_value_loopback_nes);
   else
   /*IO_CTRL_3, 0x5600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl3, ctrl_value);
   if(loopback_mode & WPX_SERDES_LANE3_LOOPBACK)
   /*IO_CTRL_4, 0x5600080 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl4, ctrl_value_loopback_nes);
   else
   /*IO_CTRL_4, 0x5600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl4, ctrl_value);

}

void WPX_SerdesInit_2_5_G_SingleLane(wpx_serdes *serdes_regs, WP_U32 serdes, WP_U8 loopback_mode)
{
   wpx_serdes_mux *mux_regs;
   wpx_serdes_single_lane *single_lane_regs;
   wpx_serdes_single_io_ctrl *single_io_control;

   mux_regs = &(serdes_regs->serdes_mux);
   single_lane_regs = &(serdes_regs->serdes_single[serdes]);
   single_io_control = &(mux_regs->io_ctrl_single[serdes]);

   /* IO_CTRL_1,0xf001 */ WPI_MEM_SET(single_io_control->single_io_ctrl1, 0xf001);
   /* IO_CTRL_1,0xf000 */ WPI_MEM_SET(single_io_control->single_io_ctrl1, 0xf000);
   /* IO_CTRL_1,0xf001 */ WPI_MEM_SET(single_io_control->single_io_ctrl1, 0xf001);
   WP_Delay(WPX_SERDES_TOGGLE_DELAY);
   /* LANE_300, 0x00003882 */ WPI_MEM_SET(single_lane_regs->lane[0], 0x00003882);
   /* CMU_001,  0x00009ed5 */ WPI_MEM_SET(single_lane_regs->cmu[1], 0x00009ed5);
   /* CMU_002,  0x00005e52 */ WPI_MEM_SET(single_lane_regs->cmu[2], 0x00005e52);
   /* CMU_003 , 0x0000d900 */ WPI_MEM_SET(single_lane_regs->cmu[3], 0x0000d900);
   /* LANE_303, 0x00000f0f */ WPI_MEM_SET(single_lane_regs->lane[3], 0x00000f0f);
   /* CMU_006 , 0x00008400 */ WPI_MEM_SET(single_lane_regs->cmu[6], 0x00008400);
   /* GPON_600, 0x0000808a */ WPI_MEM_SET(single_lane_regs->gpon[0], 0x0000808a);
   /* GPON_601, 0x00008300 */ WPI_MEM_SET(single_lane_regs->gpon[1], 0x00008300);
   /* GPON_603, 0x0200 */     WPI_MEM_SET(single_lane_regs->gpon[3], 0x0200);
   /* IO_CTRL_0, 0x00000002 */ WPI_MEM_SET(single_io_control->single_io_ctrl0, 0x0001C002);
   if(loopback_mode)
      /* IO_CTRL_1, 0x0009f801 */ WPI_MEM_SET(single_io_control->single_io_ctrl1, 0x0009f801);
   else
      /* IO_CTRL_1, 0x0001f801 */ WPI_MEM_SET(single_io_control->single_io_ctrl1, 0x0001f801);
}

void WPX_SerdesInit_2_5_G_QuadLane(wpx_serdes *serdes_regs, WP_U32 serdes, WP_U8 loopback_mode, WP_U32 isXgi)
{
   wpx_serdes_mux *mux_regs;
   wpx_serdes_quad_lane *quad_lane;
   wpx_serdes_quad_io_ctrl *quad_io_ctrl;

   WP_U32 ctrl_value = 0x07638000;
   WP_U32 ctrl_value_loopback_nes = 0x07638080;

   mux_regs = &(serdes_regs->serdes_mux);
   quad_lane = &(serdes_regs->serdes_quad[serdes-WPX_SERDES_QUAD_LANE_FIRST]);
   quad_io_ctrl = &(mux_regs->io_ctrl_quad[serdes-WPX_SERDES_QUAD_LANE_FIRST]);

   /*IO_CTRL_0, 0x000d0000*/ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl0, 0x000d0000);
   /*IO_CTRL_0, 0x000c0000*/ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl0, 0x000c0000);
   /*IO_CTRL_0, 0x000d0000*/ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl0, 0x000d0000);
   WP_Delay(WPX_SERDES_TOGGLE_DELAY);

   /*CMU002,    0x00005e0a*/ WPI_MEM_SET(quad_lane->cmu[2], 0x00005e0a);
   /*CMU001,    0x00009ed5*/ WPI_MEM_SET(quad_lane->cmu[1], 0x00009ed5);
   /*CMU000,    0x0000009c*/ WPI_MEM_SET(quad_lane->cmu[0], 0x0000009c);
   /*CMU003,    0x0000aa00*/ WPI_MEM_SET(quad_lane->cmu[3], 0x0000aa00);

   /*lane 0 addr 4, 0x0000830c */ WPI_MEM_SET(quad_lane->lane0[4], 0x0000830c );
   /*lane 0 addr 5, 0x00008000 */ WPI_MEM_SET(quad_lane->lane0[5], 0x00008000 );
   /*lane 0 addr 0, 0x00003882 */ WPI_MEM_SET(quad_lane->lane0[0], 0x00003882 );
   /*lane 0 addr 1, 0x0000726b */ WPI_MEM_SET(quad_lane->lane0[1], 0x0000726b );
   /*lane 0 addr 3, 0x00000f14 */ WPI_MEM_SET(quad_lane->lane0[3], 0x00000f14 );

   /*lane 1 addr 0, 0x00003882 */ WPI_MEM_SET(quad_lane->lane1[0], 0x00003882 );
   /*lane 1 addr 1, 0x0000726b */ WPI_MEM_SET(quad_lane->lane1[1], 0x0000726b );
   /*lane 1 addr 3, 0x00000f14 */ WPI_MEM_SET(quad_lane->lane1[3], 0x00000f14 );
   /*lane 1 addr 4, 0x0000830c */ WPI_MEM_SET(quad_lane->lane1[4], 0x0000830c );
   /*lane 1 addr 5, 0x00008000 */ WPI_MEM_SET(quad_lane->lane1[5], 0x00008000 );

   /*lane 2 addr 0, 0x00003882 */ WPI_MEM_SET(quad_lane->lane2[0], 0x00003882 );
   /*lane 2 addr 1, 0x0000726b */ WPI_MEM_SET(quad_lane->lane2[1], 0x0000726b );
   /*lane 2 addr 3, 0x00000f14 */ WPI_MEM_SET(quad_lane->lane2[3], 0x00000f14 );
   /*lane 2 addr 4, 0x0000830c */ WPI_MEM_SET(quad_lane->lane2[4], 0x0000830c );
   /*lane 2 addr 5, 0x00008000 */ WPI_MEM_SET(quad_lane->lane2[5], 0x00008000 );

   /*lane 3 addr 0, 0x00003882 */ WPI_MEM_SET(quad_lane->lane3[0], 0x00003882 );
   /*lane 3 addr 1, 0x0000726b */ WPI_MEM_SET(quad_lane->lane3[1], 0x0000726b );
   /*lane 3 addr 3, 0x00000f14 */ WPI_MEM_SET(quad_lane->lane3[3], 0x00000f14 );
   /*lane 3 addr 4, 0x0000830c */ WPI_MEM_SET(quad_lane->lane3[4], 0x0000830c );
   /*lane 3 addr 5, 0x00008000 */ WPI_MEM_SET(quad_lane->lane3[5], 0x00008000 );



   if (isXgi) /* errata 44 workaround, disable 'lock en' comma block */
   {
      /* Go to WPX_SerdesLockEnBlockDisable description for more details regarding this */
      WPX_SerdesLockEnBlockDisable(&ctrl_value, &ctrl_value_loopback_nes);      
   }

   if(loopback_mode & WPX_SERDES_LANE0_LOOPBACK)
   /*IO_CTRL_1, 0x7600080 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl1, ctrl_value_loopback_nes);
   else
   /*IO_CTRL_1, 0x7600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl1, ctrl_value);
   if(loopback_mode & WPX_SERDES_LANE1_LOOPBACK)
   /*IO_CTRL_2, 0x7600080 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl2, ctrl_value_loopback_nes);
   else
   /*IO_CTRL_2, 0x7600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl2, ctrl_value);
   if(loopback_mode & WPX_SERDES_LANE2_LOOPBACK)
   /*IO_CTRL_3, 0x7600080 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl3, ctrl_value_loopback_nes);
   else
   /*IO_CTRL_3, 0x7600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl3, ctrl_value);
   if(loopback_mode & WPX_SERDES_LANE3_LOOPBACK)
   /*IO_CTRL_4, 0x7600080 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl4, ctrl_value_loopback_nes);
   else
   /*IO_CTRL_4, 0x7600000 */ WPI_MEM_SET(quad_io_ctrl->quad_io_ctrl4, ctrl_value);
}

/*****************************************************************************
 *
 * Function: WPX_SerdesLockEnBlockDisable
 *
 * Purpose: This function is responsible for disabling the Lock-Enable block in the serdes
 *          (ERRATA-44)
 *
 * Description:
 *          Because of Err-44 (XGI synchornization problem) , this block must be turned off
 *          This function must be called on serdes initialization.
 *
 * Inputs:
 *
 *     quad_io_ctrl_value                  the value of quad io ctrl register to be written
 *     quad_io_ctrl_value_loopback_nes     the value of quad io ctrl register to be written (loopback mode)
 *
 * Outputs:
 *     in input params.
 *
 * Return Value:
 *
 * Called by: WPX_SerdesInit_2_5_G_QuadLane function
 *
 *
 ****************************************************************************/
static void WPX_SerdesLockEnBlockDisable(WP_U32 *quad_io_ctrl_value,
                                         WP_U32 *quad_io_ctrl_value_loopback_nes)
{
   *quad_io_ctrl_value              &= ~(WPX_SERDESx_IO_CTRLy_LOCK_ENA);
   *quad_io_ctrl_value_loopback_nes &= ~(WPX_SERDESx_IO_CTRLy_LOCK_ENA);
}

WP_status WPX_SetSerdesMux(WP_U32 wpid,
                           wpx_board_configuration configuration)
{
   wpx_serdes_mux_ctrl* data, data_get;
   wpx_serdes_mux_ctrl *serdes_mux_reg;
   wpx_serdes *serdes_reg;

   data = &serdes_mux_configurations[configuration];
   serdes_reg = WPX_SerdesBaseGet(wpid);
   serdes_mux_reg = &serdes_reg->serdes_mux.mux_ctrl;

   WPI_MEM_GET(data_get.mux_ctrl0, serdes_mux_reg->mux_ctrl0);
   WPI_MEM_GET(data_get.mux_ctrl1, serdes_mux_reg->mux_ctrl1);

   if(WPX_SerdesUsedByPCIe(wpid, WPX_SERDES0))
   {
      data->mux_ctrl0 &= ~SERDES_MUX_CTRL0_SERDES0_MASK;
      data->mux_ctrl0 |= data_get.mux_ctrl0 & SERDES_MUX_CTRL0_SERDES0_MASK;
      data->mux_ctrl1 &= ~SERDES_MUX_CTRL1_SERDES0_MASK;
      data->mux_ctrl1 |= data_get.mux_ctrl1 & SERDES_MUX_CTRL1_SERDES0_MASK;
   }
   else if(WPX_SerdesUsedByPCIe(wpid, WPX_SERDES1))
   {
      data->mux_ctrl0 &= ~SERDES_MUX_CTRL0_SERDES1_MASK;
      data->mux_ctrl0 |= data_get.mux_ctrl0 & SERDES_MUX_CTRL0_SERDES1_MASK;
      data->mux_ctrl1 &= ~SERDES_MUX_CTRL1_SERDES1_MASK;
      data->mux_ctrl1 |= data_get.mux_ctrl1 & SERDES_MUX_CTRL1_SERDES1_MASK;
   }

   WPI_MEM_SET(serdes_mux_reg->mux_ctrl0, data->mux_ctrl0);
   WPI_MEM_SET(serdes_mux_reg->mux_ctrl1, data->mux_ctrl1);

   return WP_OK;
}

WP_status WPX_SerdesMuxPrint(WP_U32 wpid)
{
   wpx_serdes_mux_ctrl data;
   wpx_serdes_mux_ctrl *serdes_mux_reg;
   wpx_serdes *serdes_reg;

   serdes_reg = WPX_SerdesBaseGet(wpid);
   serdes_mux_reg = &serdes_reg->serdes_mux.mux_ctrl;

   WPI_MEM_GET(data.mux_ctrl0, serdes_mux_reg->mux_ctrl0);
   WPI_MEM_GET(data.mux_ctrl1, serdes_mux_reg->mux_ctrl1);

   printf("WPX_SetSerdesMuxPrint %08X %08X\n", data.mux_ctrl0, data.mux_ctrl1);

   return WP_OK;
}

WP_boolean WPX_SerdesUsedByPCIe(WP_U32 wpid, WP_U32 serdes)
{
   wpx_serdes_mux_ctrl data;
   wpx_serdes_mux_ctrl *serdes_mux_reg;
   wpx_serdes *serdes_reg;

   serdes_reg = WPX_SerdesBaseGet(wpid);
   serdes_mux_reg = &serdes_reg->serdes_mux.mux_ctrl;

   WPI_MEM_GET(data.mux_ctrl0, serdes_mux_reg->mux_ctrl0);
   WPI_MEM_GET(data.mux_ctrl1, serdes_mux_reg->mux_ctrl1);

   if(serdes == WPX_SERDES0)
   {
      if((data.mux_ctrl0 & SERDES_MUX_CTRL0_SERDES0_MASK) == SERDES_MUX_CTRL0_SERDES0_PCIE)
         return WP_TRUE;
   }
   else if(serdes == WPX_SERDES1)
   {
      if((data.mux_ctrl0 & SERDES_MUX_CTRL0_SERDES1_MASK) == SERDES_MUX_CTRL0_SERDES1_PCIE)
         return WP_TRUE;
   }
   return WP_FALSE;
}

WP_status WPX_SerDesSet(WP_U32 wpid,
                        wpx_board_configuration configuration)
{
   WP_status status;
   WP_U32    Serdes2isXgi = 0;


   switch(configuration)
   {
      case WPX_CONFIGURE_DEFAULT_CHECKIN:
      case WPX_CONFIGURE_1UPI_1XGI_4GMII_8SGMII:
      case WPX_CONFIGURE_1XGI_6RGMII_6SGMII:
      case WPX_CONFIGURE_1UPI_1XGI_6RTBI_6SGMII:
      case WPX_CONFIGURE_1XGI_6SMII_6SGMII:
      case WPX_CONFIGURE_2RMII_8TDI_1XGI_10SGMII:
      case WPX_CONFIGURE_8TDI_1UPI_1XGI_10SGMII:
         Serdes2isXgi = WPX_SERDES_XGI;
         // fallthrough
      case WPX_CONFIGURE_CHECKIN_TDI_16:
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetSingleLane(wpid, WPX_SERDES0, WPX_SERDES_1G, WPX_SERDES_NORMAL));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetSingleLane(wpid, WPX_SERDES1, WPX_SERDES_1G, WPX_SERDES_NORMAL));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES2, WPX_SERDES_2_5G, WPX_SERDES_NORMAL,Serdes2isXgi));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES3, WPX_SERDES_1G, WPX_SERDES_NORMAL,WPX_SERDES_NOT_XGI));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES4, WPX_SERDES_1G, WPX_SERDES_NORMAL,WPX_SERDES_NOT_XGI));
         break;
      case WPX_CONFIGURE_2UPI_2XGI_6SGMII2G:
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetSingleLane(wpid, WPX_SERDES0, WPX_SERDES_2_5G, WPX_SERDES_NORMAL));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetSingleLane(wpid, WPX_SERDES1, WPX_SERDES_2_5G, WPX_SERDES_NORMAL));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES2, WPX_SERDES_2_5G, WPX_SERDES_NORMAL,WPX_SERDES_XGI));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES3, WPX_SERDES_2_5G, WPX_SERDES_NORMAL,WPX_SERDES_XGI));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES4, WPX_SERDES_2_5G, WPX_SERDES_NORMAL,WPX_SERDES_NOT_XGI));
         break;
      case WPX_CONFIGURE_2SGMII_2SGMII2G_16TDI:
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetSingleLane(wpid, WPX_SERDES0, WPX_SERDES_1G, WPX_SERDES_NORMAL));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetSingleLane(wpid, WPX_SERDES1, WPX_SERDES_1G, WPX_SERDES_NORMAL));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES4, WPX_SERDES_2_5G, WPX_SERDES_NORMAL,WPX_SERDES_NOT_XGI));
         break;
      case WPX_CONFIGURE_6SGMII_1SGMII2G_2SMII:
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetSingleLane(wpid, WPX_SERDES0, WPX_SERDES_1G, WPX_SERDES_NORMAL));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetSingleLane(wpid, WPX_SERDES1, WPX_SERDES_1G, WPX_SERDES_NORMAL));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES3, WPX_SERDES_2_5G, WPX_SERDES_NORMAL, WPX_SERDES_NOT_XGI));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES4, WPX_SERDES_1G, WPX_SERDES_NORMAL, WPX_SERDES_NOT_XGI));
         break;
         
      case WPX_CONFIGURE_2UPI_L3_2XGI_6SGMII:      
      case WPX_CONFIGURE_2XGI_6SGMII:      
         WPI_RETURN_IF_ERROR(status, 
                             WPX_SerdesSetSingleLane(wpid, WPX_SERDES0, WPX_SERDES_1G, WPX_SERDES_NORMAL));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetSingleLane(wpid, WPX_SERDES1, WPX_SERDES_1G, WPX_SERDES_NORMAL));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES2, WPX_SERDES_2_5G, WPX_SERDES_NORMAL, WPX_SERDES_XGI));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES3, WPX_SERDES_2_5G, WPX_SERDES_NORMAL, WPX_SERDES_XGI));
         WPI_RETURN_IF_ERROR(status,
                             WPX_SerdesSetQuadLane(wpid, WPX_SERDES4, WPX_SERDES_1G, WPX_SERDES_NORMAL, WPX_SERDES_NOT_XGI));
         break;
      case WPX_CONFIGURE_UPI1_TDI8_16_10SGMII:
         WPI_RETURN_IF_ERROR(status,
                              WPX_SerdesSetSingleLane(wpid, WPX_SERDES0, WPX_SERDES_1G, WPX_SERDES_NORMAL));
          WPI_RETURN_IF_ERROR(status,
                              WPX_SerdesSetSingleLane(wpid, WPX_SERDES1, WPX_SERDES_1G, WPX_SERDES_NORMAL));
          WPI_RETURN_IF_ERROR(status,
                              WPX_SerdesSetQuadLane(wpid, WPX_SERDES3, WPX_SERDES_1G, WPX_SERDES_NORMAL, WPX_SERDES_NOT_XGI));
          WPI_RETURN_IF_ERROR(status,
                              WPX_SerdesSetQuadLane(wpid, WPX_SERDES4, WPX_SERDES_1G, WPX_SERDES_NORMAL, WPX_SERDES_NOT_XGI));

      default:
         break;
   }

   /* Serdes mux configuration */
   WPI_RETURN_IF_ERROR(status,
                       WPX_SetSerdesMux(wpid, configuration));

   return status;
}

WP_status WPX_BoardSerdesInit( WP_U32 wpid,
                               WP_port port,
                               WP_U32 loopback_mode)
{
   WP_status status;
   WPX_SERDES_LANES serdes_index;
   WP_U32 lane_index;
   WP_U32 rate;
   wpx_port_to_serdes_connection *serdes_data;
   wpx_serdes_lane_data *serdes_lane_data;

   if((port < WP_PORT_ENET1) || (port > WP_PORT_XGI2))
      return WPI_ERROR(WP_ERR_CONFIG);

   serdes_data =  &(port_to_serdes[current_configuration]);
   serdes_lane_data = &(serdes_data->lane_data[port-WP_PORT_ENET1]);

   serdes_index = serdes_lane_data->serdes_index;
   lane_index = serdes_lane_data->lane_index;
   rate = serdes_lane_data->rate;

   if(serdes_index == WPX_SERDES_NA ||
      lane_index == WPX_SERDES_LANE_NA ||
      rate == WPX_SERDES_RATE_NA)
      return WPI_ERROR(WP_ERR_CONFIG);

   if(lane_index != WPX_SERDES_LANE_ALL)
   {
      if(loopback_mode == WPX_SERDES_LOOPBACK)
      {
         serdes_loopback_mode[serdes_index] |= 1<<lane_index;
      }
      else
      {
         serdes_loopback_mode[serdes_index] &= ~(1<<lane_index);
      }
   }
   else
   {
      if(loopback_mode == WPX_SERDES_LOOPBACK)
      {
         serdes_loopback_mode[serdes_index] |= 0xf;
      }
      else
      {
         serdes_loopback_mode[serdes_index] &= ~(0xf);
      }
   }

   if (serdes_index >= WPX_SERDES_SINGLE_LANE_FIRST && serdes_index <= WPX_SERDES_SINGLE_LANE_LAST)
   {
      WPX_SerdesSetSingleLane(wpid,
                              serdes_index,
                              rate,
                              serdes_loopback_mode[serdes_index]);
   }
   else if(serdes_index >= WPX_SERDES_QUAD_LANE_FIRST &&
           serdes_index <= WPX_SERDES_QUAD_LANE_LAST)
   {

	  WP_U32 isXgi = WPX_SERDES_NOT_XGI;

	  if (port == WP_PORT_XGI1 || port == WP_PORT_XGI2)
	     isXgi = WPX_SERDES_XGI;

      WPI_RETURN_IF_ERROR(status,
                          WPX_SerdesSetQuadLane(wpid,
                                                serdes_index,
                                                rate,
                                                serdes_loopback_mode[serdes_index],
                                                isXgi));
   }
   else
      return WPI_ERROR(WP_ERR_CONFIG);

   return WP_OK;
}


