#ifndef __MORRIS_COFIG_H__
#define __MORRIS_COFIG_H__

#define MORRIS_CR_ON	(1)

#define USE_MORRIS_CONFIG	(0)
#define USE_MORRIS_REF_CLOCK	WPX_UFE_FRAMER_TRANSMIT_TIMING_INPUT_REFERENCE_CLOCK


#define MORRIS_ENABLE_PM_PRINT_COUNTER	(1)
#define MORRIS_PM_PORT_PRINT_WITHOUT_COUNTER	(0)


#define MORRIS_ENABLE_STM_1	(0)
#define MORRIS_SKIP_ALARMS	(1)


#define MORRIS_USE_VC4	(1)
#define MORRIS_DISABLE_MON_STATE	(0)


#define MORRIS_FACTOR	(1)


#endif


