#ifndef  _OMIINO_FRAMER_LLC_MESSAGE_CATALOGUE_PUBLIC_
#define  _OMIINO_FRAMER_LLC_MESSAGE_CATALOGUE_PUBLIC_


/*
	About: Copyright

	Copyright (c) 2010  Omiino Ltd

	All rights reserved.  

	This code is provided under license and or Non-disclosure     
	Agreement and must be used solely for the purpose for which it
	was provided. 

	It must not be passed to any third party without
	the written permission of Omiino Ltd.   

	Visit <http://www.omiino.com> or send messages to support@omiino.com.


*/






#ifdef __cplusplus
extern "C"
{
#endif

#define OMIINO_MESSAGE_CATALOGUE_NULL_MESSAGE                                                                                                       (0xFFFFFFFF)

#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEFAULT_RAM_IGNORE                                                                        (0)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_SET_MODE                                                                           (1)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_SET_FRAME_ALIGNMENT_OFFSET                                                         (2)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_CREATE_FACILITY                                                      (3)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_CREATE_FACILITY                                              (4)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_CREATE_FACILITY                                                (5)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_DELETE_FACILITY                                                      (6)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DELETE_FACILITY                                              (7)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_DELETE_FACILITY                                                (8)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_SET_RATE                                                        (9)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_ENABLE_SCRAMBLING                                               (10)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_DISABLE_SCRAMBLING                                              (11)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_DIAGNOSTIC_LOOPBACK_ENABLE_SHALLOW                              (12)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_DIAGNOSTIC_LOOPBACK_DISABLE_SHALLOW                             (13)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_DIAGNOSTIC_LOOPBACK_ENABLE_DEEP                                 (14)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_DIAGNOSTIC_LOOPBACK_DISABLE_DEEP                                (15)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_SECTION_J0_SET_MODE                                             (16)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_SECTION_J0_SET_TX                                               (17)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_SECTION_J0_SET_EX                                               (18)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_SECTION_B1_SET_EXCESSIVE_THRESHOLD                              (19)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_SECTION_B1_SET_SIGNAL_DEGRADE_THRESHOLD                         (20)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_LINE_B2_SET_EXCESSIVE_THRESHOLD                                 (21)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_LINE_B2_SET_SIGNAL_DEGRADE_THRESHOLD                            (22)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_HO_PATH_J1_SET_MODE                                                  (23)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_HO_PATH_J1_SET_TX                                                    (24)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_HO_PATH_J1_SET_EX                                                    (25)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_HO_PATH_C2_SET_TX                                                    (26)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_HO_PATH_C2_SET_EX                                                    (27)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_HO_PATH_B3_SET_EXCESSIVE_THRESHOLD                                   (28)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_HO_PATH_B3_SET_SIGNAL_DEGRADE_THRESHOLD                              (29)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_LO_PATH_J2_SET_TX                                                    (30)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_LO_PATH_J2_SET_EX                                                    (31)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_LO_PATH_V5_SIGNAL_LABEL_SET_TX                                       (32)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_LO_PATH_V5_SIGNAL_LABEL_SET_EX                                       (33)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_LO_PATH_V5_BIP2_SET_EXCESSIVE_THRESHOLD                              (34)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_LO_PATH_V5_BIP2_SET_SIGNAL_DEGRADE_THRESHOLD                         (35)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_SET_FRAMING                                                  (36)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_SET_MAPPING                                                  (37)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_SET_CLOCK_RECOVERY                                           (38)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_ENABLE_CAS                                                   (39)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DISABLE_CAS                                                  (40)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_AIS_CONTROL_ENABLE_TOWARDS_SOCKET                            (41)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_AIS_CONTROL_DISABLE_TOWARDS_SOCKET                           (42)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_AIS_CONTROL_ENABLE_TOWARDS_LINE                              (43)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_AIS_CONTROL_DISABLE_TOWARDS_LINE                             (44)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DIAGNOSTIC_DRIVE_RECOVERED_CLOCK                             (45)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DIAGNOSTIC_LOOPBACK_ENABLE_SHALLOW                           (46)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DIAGNOSTIC_LOOPBACK_DISABLE_SHALLOW                          (47)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DIAGNOSTIC_LOOPBACK_ENABLE_DEEP                              (48)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DIAGNOSTIC_LOOPBACK_DISABLE_DEEP                             (49)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DIAGNOSTIC_INGRESS_TERM_PRBS_SET                             (50)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DIAGNOSTIC_INGRESS_GEN_PRBS_SET                              (51)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DIAGNOSTIC_EGRESS_TERM_PRBS_SET                              (52)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DIAGNOSTIC_EGRESS_GEN_PRBS_SET                               (53)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_SET_BANDWIDTH                                                  (54)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_SET_FRAMING                                                    (55)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_SET_MAPPING                                                    (56)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_SET_CLOCK_RECOVERY                                             (57)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_ENABLE_CAS                                                     (58)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_DISABLE_CAS                                                    (59)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_AIS_CONTROL_ENABLE_TOWARDS_SOCKET                              (60)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_AIS_CONTROL_DISABLE_TOWARDS_SOCKET                             (61)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_AIS_CONTROL_ENABLE_TOWARDS_LINE                                (62)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_AIS_CONTROL_DISABLE_TOWARDS_LINE                               (63)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_DIAGNOSTIC_LOOPBACK_ENABLE_SHALLOW                             (64)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_DIAGNOSTIC_LOOPBACK_DISABLE_SHALLOW                            (65)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_DIAGNOSTIC_LOOPBACK_ENABLE_DEEP                                (66)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_DISCRETE_CLIENT_DIAGNOSTIC_LOOPBACK_DISABLE_DEEP                               (67)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_CONNECTIONS_THROUGH_CREATE_CONNECTION                                                     (68)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_CONNECTIONS_THROUGH_DELETE_CONNECTION                                                     (69)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_CONNECTIONS_ADD_DROP_TO_CLIENT_SOCKET_CREATE_CONNECTION                       			(70)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_CONNECTIONS_ADD_DROP_TO_CLIENT_SOCKET_DELETE_CONNECTION                       			(71)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_CONNECTIONS_ADD_DROP_DISCRETE_CLIENT_TO_CLIENT_SOCKET_CREATE_CONNECTION       			(72)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_CONNECTIONS_ADD_DROP_DISCRETE_CLIENT_TO_CLIENT_SOCKET_DELETE_CONNECTION       			(73)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_DRIVER_SONET_SDH_ENABLE_ALARM_REPORTING_FOR_ALARM_CATEGORY                         (74)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_DRIVER_SONET_SDH_DISABLE_ALARM_REPORTING_FOR_ALARM_CATEGORY                        (76)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_DRIVER_SOCKET_CLIENT_ENABLE_ALARM_REPORTING_FOR_ALARM_CATEGORY                     (77)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_DRIVER_SOCKET_CLIENT_DISABLE_ALARM_REPORTING_FOR_ALARM_CATEGORY                    (78)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_DIAGNOSTIC_DRIVE_RECOVERED_CLOCK                                (79)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_DIAGNOSTIC_LOOPBACK_ENABLE											(80)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_DIAGNOSTIC_LOOPBACK_DISABLE											(81)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_FORCE_A															(82)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_FORCE_B															(83)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_SET_BUILD_VARIANT																	(84)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_BOOTLOADER_DATA_PACKET																	(85)
#define OMINNO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_BOOTLOADER_START_FIRMWARE																	(86)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_RESET																						(87)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DRIVER_PRODUCT_RELEASE																	(88)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DRIVER_SOFTWARE_BUILD_DATE																(89)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DRIVER_SOFTWARE_BUILD_VERSION																(90)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_SET_TIMESTAMP_BYTE_COUNT										(91)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_PERFORMANCE_MONITORING_SONET_SDH_PORT_ENABLE_MONITORING									(92)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_PERFORMANCE_MONITORING_SONET_SDH_PORT_DISABLE_MONITORING									(93)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_PERFORMANCE_MONITORING_SONET_SDH_HIGH_ORDER_PATH_ENABLE_MONITORING						(94)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_PERFORMANCE_MONITORING_SONET_SDH_HIGH_ORDER_PATH_DISABLE_MONITORING						(95)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_PERFORMANCE_MONITORING_SONET_SDH_LOW_ORDER_PATH_ENABLE_MONITORING							(96)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_PERFORMANCE_MONITORING_SONET_SDH_LOW_ORDER_PATH_DISABLE_MONITORING						(97)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_PATH_ALARM_KEY_ADD																		(98)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_PORT_ALARM_KEY_ADD																		(99)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_ENABLE_TIMESTAMPING											(100)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_DISABLE_TIMESTAMPING											(101)

#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_PM_E1_ENABLE_MONITORING																					(102)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_PM_E1_DISABLE_MONITORING																				(103)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_PM_T1_ENABLE_MONITORING																					(104)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_PM_T1_DISABLE_MONITORING																				(105)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_SOCKET_CLIENT_ALARM_KEY_ADD																(106)

#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_DRIVER_DISCRETE_CLIENT_ENABLE_ALARM_REPORTING_FOR_ALARM_CATEGORY                   (107)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_DRIVER_DISCRETE_CLIENT_DISABLE_ALARM_REPORTING_FOR_ALARM_CATEGORY                  (108)

#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_SET_PROTECTION_MODE                                                                (110)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_DRIVER_SONET_SDH_ENABLE_ALARM_REPORTING_FOR_ALARM_CATEGORY_FOR_LINE_ENDPOINT		(111)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_DRIVER_SONET_SDH_DISABLE_ALARM_REPORTING_FOR_ALARM_CATEGORY_FOR_LINE_ENDPOINT		(112)

#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_DCC_ENABLE														(113)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_DCC_DISABLE														(114)

#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_SET_CARD_PROTECTION_OPERATING_MODE													(115)

#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_DEVICE_SET_AIS_INSERTION_MODE																(116)

#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_HO_PATH_ERDI_SET_MODE                                                (117)

#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_HO_PATH_RDI_SET_MODE                                                (117)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_RDI_CONTROL_ENABLE_TOWARDS_LINE                              (118)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_RDI_CONTROL_DISABLE_TOWARDS_LINE                             (119)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_PM_E3T3_ENABLE_MONITORING																					(120)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_PM_E3T3_DISABLE_MONITORING																				(121)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_SQUELCH_RECOVERED_CLOCK											(122)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_HO_PATH_SS_BITS_SET_TX                                               (123)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_HO_PATH_SS_BITS_GET_RX                                               (124)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SONET_SDH_PORT_SFP_SET_STATE                                                        (125)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_FACILITIES_SOCKET_CLIENT_PDH_E3T3_SET_FEAC                                           (126)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_CONFIGURATION_MAX_MESSAGES																				(127)




#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_SIGNALLING_DEFAULT_RAM_IGNORE                                                                           (0)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_SIGNALLING_SONET_SDH_PORT_K1K2_SET_TX																	(1)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_SIGNALLING_SONET_SDH_PORT_S1_SET_TX																		(2)
#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_SIGNALLING_MAX_MESSAGES																					(3)

#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_SIGNALLING_DEFAULT_RAM_IGNORE                                                                           (0)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_SIGNALLING_S1_CHANGE                                                                                    (1)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_SIGNALLING_K1K2_CHANGE                                                                                  (2)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_SIGNALLING_PORT_ALARM_CHANGE                                                                            (3)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_SIGNALLING_MAX_MESSAGES                                                                                 (4)

#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_STATUS_DEFAULT_RAM_IGNORE                                                                               (0)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_ALARM                                                                                            (1)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_C2                                                                                               (2)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_J0                                                                                               (3)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_J1                                                                                               (4)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_J2                                                                                               (5)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_V5_SIGNAL_LABEL                                                                                  (6)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_PRODUCT_HARDWARE_INFORMATION                                                                     (7)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_PRODUCT_FIRMWARE_INFORMATION                                                                     (8)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_REQUEST_DRIVER_INFORMATION																		(9)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_PRBS_SOCKET_INGRESS																				(10)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_PRBS_SOCKET_EGRESS																				(11)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_SS_BITS                                                                                          (12)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_STATUS_MAX_MESSAGES                                                                                     (13)

#define OMIINO_SOUTHBOUND_MESSAGE_CATALOGUE_PERFORMANCE_MONITORING_DEFAULT_RAM_IGNORE                                                               (0)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_PERFORMANCE_MONITORING_LINE_PORT                                                                        (1)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_PERFORMANCE_MONITORING_HO                                                                               (2)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_PERFORMANCE_MONITORING_LO                                                                               (3)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_PERFORMANCE_MONITORING_DISCRETE_CLIENT                                                                  (4)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_PERFORMANCE_MONITORING_PDH																				(5)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_PERFORMANCE_MONITORING_MAX_MESSAGES                                                                     (6)

#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_OMNISPY_DEFAULT_RAM_IGNORE																				(0)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_OMNISPY_TO_APPLICATION																					(1)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_OMNISPY_VIRTUAL_SCREEN_NEXT_PAGE																		(2)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_OMNISPY_VIRTUAL_SCREEN_PREV_PAGE																		(3)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_OMNISPY_VIRTUAL_SCREEN_REFRESH																			(4)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_OMNISPY_PEEK_RESPONSE																					(5)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_OMNISPY_BLOCK_POKE_VERIFY_RESPONSE																		(6)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_OMNISPY_MAX_MESSAGES																					(7)

#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_OMNISPY_RELAY_NORTHBOUND_DATAGRAM_EXIT																	(0)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_OMNISPY_RELAY_NORTHBOUND_DATAGRAM_QC																	(1)
#define OMIINO_NORTHBOUND_MESSAGE_CATALOGUE_OMNISPY_RELAY_NORTHBOUND_DATAGRAM_LIST_FACILITIES														(2)




#ifdef __cplusplus
}
#endif


#endif /* _OMIINO_FRAMER_LLC_MESSAGE_CATALOGUE_PUBLIC_ */
