;STRUCTURES
exehead         STRUC
exSignature     DW      ?
exExtraByte     DW      ?
exPages         DW      ?
exRelocItems    DW      ?
exHeaderSize    DW      ?
exMinAlloc      DW      ?
exMaxAlloc      DW      ?
exInitSS        DW      ?
exInitSP        DW      ?
exCheckSum      DW      ?
exInitIP        DW      ?
exInitCS        DW      ?
exRelocTable    DW      ?
exOverlay       DW      ?
exehead         ENDS
