/*****************************************************************************
 * (C) Copyright 2000-2006, Wintegra. All rights reserved.
 * WINTEGRA CONFIDENTIAL PROPRIETARY
 * Contains Confidential Proprietary information of Wintegra.
 * Reverse engineering is prohibited.
 * The copyright notice does not imply publication.
 ****************************************************************************/

/*****************************************************************************
 *
 * File: wufei_hw_tdm.h
 *
 * Purpose: the UFE TDM  macro and structures
 *
 ****************************************************************************/
#ifndef WUFEI_HW_TDM_H
#define WUFEI_HW_TDM_H

typedef struct
{
      WP_U8  idle_cas_nibble;  /* TDM idle CAS pattern  */
      WP_U8  idle_data_byte;   /* TDM idle DATA pattern  */
      WP_U16 reserved;
}WUFEI_hw_idle_pattern;

typedef struct
{
      WP_U32 int0;
      WP_U32 int1;
      WP_U32 intm0;
      WP_U32 intm1;
}WUFEI_hw_tdm_int;

typedef struct
{
      WP_U16 port_id;
      WP_U16 config;
}WUFEI_hw_tdm_lpbk_system;

typedef struct
{
      WP_U16 config;
      WP_U16 status;
}WUFEI_hw_tdm_lpbk_line;

#define WUFEI_N_SLOT_PER_LINE (WUFE_N_SLOTS_E1)

#define WUFEI_hw_tdm_entry   WP_U16

#define WUFEI_TDM_ENTRY_SLOT_ID_S (0)
#define WUFEI_TDM_ENTRY_SLOT_ID_W (5)
#define WUFEI_TDM_ENTRY_SLOT_ID_F(v) WUFEI_FIELD(v, WUFEI_TDM_ENTRY_SLOT_ID_S)
#define WUFEI_TDM_ENTRY_SLOT_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_ENTRY_SLOT_ID_S, WUFEI_TDM_ENTRY_SLOT_ID_W)
#define WUFEI_TDM_ENTRY_SLOT_ID_M \
        WUFEI_MASK(WUFEI_TDM_ENTRY_SLOT_ID_S, WUFEI_TDM_ENTRY_SLOT_ID_W)

#define WUFEI_TDM_ENTRY_TU_ID_S (5)
#define WUFEI_TDM_ENTRY_TU_ID_W (2)
#define WUFEI_TDM_ENTRY_TU_ID_F(v) WUFEI_FIELD(v, WUFEI_TDM_ENTRY_TU_ID_S)
#define WUFEI_TDM_ENTRY_TU_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_ENTRY_TU_ID_S, WUFEI_TDM_ENTRY_TU_ID_W)
#define WUFEI_TDM_ENTRY_TU_ID_M \
        WUFEI_MASK(WUFEI_TDM_ENTRY_TU_ID_S, WUFEI_TDM_ENTRY_TU_ID_W)

#define WUFEI_TDM_ENTRY_TUG2_ID_S (7)
#define WUFEI_TDM_ENTRY_TUG2_ID_W (3)
#define WUFEI_TDM_ENTRY_TUG2_ID_F(v) WUFEI_FIELD(v, WUFEI_TDM_ENTRY_TUG2_ID_S)
#define WUFEI_TDM_ENTRY_TUG2_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_ENTRY_TUG2_ID_S, WUFEI_TDM_ENTRY_TUG2_ID_W)
#define WUFEI_TDM_ENTRY_TUG2_ID_M \
        WUFEI_MASK(WUFEI_TDM_ENTRY_TUG2_ID_S, WUFEI_TDM_ENTRY_TUG2_ID_W)

#define WUFEI_TDM_ENTRY_SPE_ID_S (10)
#define WUFEI_TDM_ENTRY_SPE_ID_W (2)
#define WUFEI_TDM_ENTRY_SPE_ID_F(v) WUFEI_FIELD(v, WUFEI_TDM_ENTRY_SPE_ID_S)
#define WUFEI_TDM_ENTRY_SPE_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_ENTRY_SPE_ID_S, WUFEI_TDM_ENTRY_SPE_ID_W)
#define WUFEI_TDM_ENTRY_SPE_ID_M \
        WUFEI_MASK(WUFEI_TDM_ENTRY_SPE_ID_S, WUFEI_TDM_ENTRY_SPE_ID_W)

#define WUFEI_TDM_ENTRY_STM1_ID_S (12)
#define WUFEI_TDM_ENTRY_STM1_ID_W (1)
#define WUFEI_TDM_ENTRY_STM1_ID_F(v) WUFEI_FIELD(v, WUFEI_TDM_ENTRY_STM1_ID_S)
#define WUFEI_TDM_ENTRY_STM1_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_ENTRY_STM1_ID_S, WUFEI_TDM_ENTRY_STM1_ID_W)
#define WUFEI_TDM_ENTRY_STM1_ID_M \
        WUFEI_MASK(WUFEI_TDM_ENTRY_STM1_ID_S, WUFEI_TDM_ENTRY_STM1_ID_W)

#define WUFEI_TDM_ENTRY_PHY_ID_S (0)
#define WUFEI_TDM_ENTRY_PHY_ID_W (12)
#define WUFEI_TDM_ENTRY_PHY_ID_F(v) WUFEI_FIELD(v, WUFEI_TDM_ENTRY_PHY_ID_S)
#define WUFEI_TDM_ENTRY_PHY_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_ENTRY_PHY_ID_S, WUFEI_TDM_ENTRY_PHY_ID_W)
#define WUFEI_TDM_ENTRY_PHY_ID_M \
        WUFEI_MASK(WUFEI_TDM_ENTRY_PHY_ID_S, WUFEI_TDM_ENTRY_PHY_ID_W)

#define WUFEI_TDM_ENTRY_FIRST_S (14)
#define WUFEI_TDM_ENTRY_FIRST_W (1)
#define WUFEI_TDM_ENTRY_FIRST_F(v) WUFEI_FIELD(v, WUFEI_TDM_ENTRY_FIRST_S)
#define WUFEI_TDM_ENTRY_FIRST_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_ENTRY_FIRST_S, WUFEI_TDM_ENTRY_FIRST_W)
#define WUFEI_TDM_ENTRY_FIRST_M \
        WUFEI_MASK(WUFEI_TDM_ENTRY_FIRST_S, WUFEI_TDM_ENTRY_FIRST_W)

#define WUFEI_TDM_ENTRY_ACTIVE_S (15)
#define WUFEI_TDM_ENTRY_ACTIVE_W (1)
#define WUFEI_TDM_ENTRY_ACTIVE_F(v) WUFEI_FIELD(v, WUFEI_TDM_ENTRY_ACTIVE_S)
#define WUFEI_TDM_ENTRY_ACTIVE_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_ENTRY_ACTIVE_S, WUFEI_TDM_ENTRY_ACTIVE_W)
#define WUFEI_TDM_ENTRY_ACTIVE_M \
        WUFEI_MASK(WUFEI_TDM_ENTRY_ACTIVE_S, WUFEI_TDM_ENTRY_ACTIVE_W)

#define WUFEI_TDM_MODE_DATA_PATTERN_S (0)
#define WUFEI_TDM_MODE_DATA_PATTERN_W (8)
#define WUFEI_TDM_MODE_DATA_PATTERN_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_DATA_PATTERN_S)
#define WUFEI_TDM_MODE_DATA_PATTERN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_DATA_PATTERN_S, WUFEI_TDM_MODE_DATA_PATTERN_W)
#define WUFEI_TDM_MODE_DATA_PATTERN_M \
        WUFEI_MASK(WUFEI_TDM_MODE_DATA_PATTERN_S, WUFEI_TDM_MODE_DATA_PATTERN_W)

#define WUFEI_TDM_MODE_CAS_PATTERN_S (8)
#define WUFEI_TDM_MODE_CAS_PATTERN_W (4)
#define WUFEI_TDM_MODE_CAS_PATTERN_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_CAS_PATTERN_S)
#define WUFEI_TDM_MODE_CAS_PATTERN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_CAS_PATTERN_S, WUFEI_TDM_MODE_CAS_PATTERN_W)
#define WUFEI_TDM_MODE_CAS_PATTERN_M \
        WUFEI_MASK(WUFEI_TDM_MODE_CAS_PATTERN_S, WUFEI_TDM_MODE_CAS_PATTERN_W)

#define WUFEI_TDM_LPBK_LINE_EN_S (0)
#define WUFEI_TDM_LPBK_LINE_EN_W (1)
#define WUFEI_TDM_LPBK_LINE_EN_F(v) WUFEI_FIELD(v, WUFEI_TDM_LPBK_LINE_EN_S)
#define WUFEI_TDM_LPBK_LINE_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_LPBK_LINE_EN_S, WUFEI_TDM_LPBK_LINE_EN_W)
#define WUFEI_TDM_LPBK_LINE_EN_M \
        WUFEI_MASK(WUFEI_TDM_LPBK_LINE_EN_S, WUFEI_TDM_LPBK_LINE_EN_W)

#define WUFEI_TDM_LPBK_LINE_UNFRM_S (1)
#define WUFEI_TDM_LPBK_LINE_UNFRM_W (1)
#define WUFEI_TDM_LPBK_LINE_UNFRM_F(v) WUFEI_FIELD(v, WUFEI_TDM_LPBK_LINE_UNFRM_S)
#define WUFEI_TDM_LPBK_LINE_UNFRM_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_LPBK_LINE_UNFRM_S, WUFEI_TDM_LPBK_LINE_UNFRM_W)
#define WUFEI_TDM_LPBK_LINE_UNFRM_M \
        WUFEI_MASK(WUFEI_TDM_LPBK_LINE_UNFRM_S, WUFEI_TDM_LPBK_LINE_UNFRM_W)

#define WUFEI_TDM_LPBK_LINE_ID_S (5)
#define WUFEI_TDM_LPBK_LINE_ID_W (11)
#define WUFEI_TDM_LPBK_LINE_ID_F(v) WUFEI_FIELD(v, WUFEI_TDM_LPBK_LINE_ID_S)
#define WUFEI_TDM_LPBK_LINE_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_LPBK_LINE_ID_S, WUFEI_TDM_LPBK_LINE_ID_W)
#define WUFEI_TDM_LPBK_LINE_ID_M \
        WUFEI_MASK(WUFEI_TDM_LPBK_LINE_ID_S, WUFEI_TDM_LPBK_LINE_ID_W)

#define WUFEI_TDM_LPBK_LINE_UNDR_S (0)
#define WUFEI_TDM_LPBK_LINE_UNDR_W (1)
#define WUFEI_TDM_LPBK_LINE_UNDR_F(v) WUFEI_FIELD(v, WUFEI_TDM_LPBK_LINE_UNDR_S)
#define WUFEI_TDM_LPBK_LINE_UNDR_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_LPBK_LINE_UNDR_S, WUFEI_TDM_LPBK_LINE_UNDR_W)
#define WUFEI_TDM_LPBK_LINE_UNDR_M \
        WUFEI_MASK(WUFEI_TDM_LPBK_LINE_UNDR_S, WUFEI_TDM_LPBK_LINE_UNDR_W)

#define WUFEI_TDM_LPBK_LINE_OVR_S (1)
#define WUFEI_TDM_LPBK_LINE_OVR_W (1)
#define WUFEI_TDM_LPBK_LINE_OVR_F(v) WUFEI_FIELD(v, WUFEI_TDM_LPBK_LINE_OVR_S)
#define WUFEI_TDM_LPBK_LINE_OVR_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_LPBK_LINE_OVR_S, WUFEI_TDM_LPBK_LINE_OVR_W)
#define WUFEI_TDM_LPBK_LINE_OVR_M \
        WUFEI_MASK(WUFEI_TDM_LPBK_LINE_OVR_S, WUFEI_TDM_LPBK_LINE_OVR_W)

#define WUFEI_TDM_LPBK_SYS_EN_S (15)
#define WUFEI_TDM_LPBK_SYS_EN_W (1)
#define WUFEI_TDM_LPBK_SYS_EN_F(v) WUFEI_FIELD(v, WUFEI_TDM_LPBK_SYS_EN_S)
#define WUFEI_TDM_LPBK_SYS_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_LPBK_SYS_EN_S, WUFEI_TDM_LPBK_SYS_EN_W)
#define WUFEI_TDM_LPBK_SYS_EN_M \
        WUFEI_MASK(WUFEI_TDM_LPBK_SYS_EN_S, WUFEI_TDM_LPBK_SYS_EN_W)

#define WUFEI_TDM_LPBK_SYS_DIV_VAL_S (0)
#define WUFEI_TDM_LPBK_SYS_DIV_VAL_W (8)
#define WUFEI_TDM_LPBK_SYS_DIV_VAL_F(v) WUFEI_FIELD(v, WUFEI_TDM_LPBK_SYS_DIV_VAL_S)
#define WUFEI_TDM_LPBK_SYS_DIV_VAL_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_LPBK_SYS_DIV_VAL_S, WUFEI_TDM_LPBK_SYS_DIV_VAL_W)
#define WUFEI_TDM_LPBK_SYS_DIV_VAL_M \
        WUFEI_MASK(WUFEI_TDM_LPBK_SYS_DIV_VAL_S, WUFEI_TDM_LPBK_SYS_DIV_VAL_W)

#define WUFEI_TDM_LPBK_SYS_TRANS_MODE_S (8)
#define WUFEI_TDM_LPBK_SYS_TRANS_MODE_W (1)
#define WUFEI_TDM_LPBK_SYS_TRANS_MODE_F(v) WUFEI_FIELD(v, WUFEI_TDM_LPBK_SYS_TRANS_MODE_S)
#define WUFEI_TDM_LPBK_SYS_TRANS_MODE_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_LPBK_SYS_TRANS_MODE_S, WUFEI_TDM_LPBK_SYS_TRANS_MODE_W)
#define WUFEI_TDM_LPBK_SYS_TRANS_MODE_M \
        WUFEI_MASK(WUFEI_TDM_LPBK_SYS_TRANS_MODE_S, WUFEI_TDM_LPBK_SYS_TRANS_MODE_W)

#define WUFEI_TDM_LPBK_SYS_UNFRM_S (9)
#define WUFEI_TDM_LPBK_SYS_UNFRM_W (1)
#define WUFEI_TDM_LPBK_SYS_UNFRM_F(v) WUFEI_FIELD(v, WUFEI_TDM_LPBK_SYS_UNFRM_S)
#define WUFEI_TDM_LPBK_SYS_UNFRM_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_LPBK_SYS_UNFRM_S, WUFEI_TDM_LPBK_SYS_UNFRM_W)
#define WUFEI_TDM_LPBK_SYS_UNFRM_M \
        WUFEI_MASK(WUFEI_TDM_LPBK_SYS_UNFRM_S, WUFEI_TDM_LPBK_SYS_UNFRM_W)

#define WUFEI_TDM_LPBK_SYS_ID_S (5)
#define WUFEI_TDM_LPBK_SYS_ID_W (11)
#define WUFEI_TDM_LPBK_SYS_ID_F(v) WUFEI_FIELD(v, WUFEI_TDM_LPBK_SYS_ID_S)
#define WUFEI_TDM_LPBK_SYS_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_LPBK_SYS_ID_S, WUFEI_TDM_LPBK_SYS_ID_W)
#define WUFEI_TDM_LPBK_SYS_ID_M \
        WUFEI_MASK(WUFEI_TDM_LPBK_SYS_ID_S, WUFEI_TDM_LPBK_SYS_ID_W)

/*requests assertion to FM in Tx direction - active high*/
#define WUFEI_TDM_MODE_TX_EN_S (0)
#define WUFEI_TDM_MODE_TX_EN_W (1)
#define WUFEI_TDM_MODE_TX_EN_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_TX_EN_S)
#define WUFEI_TDM_MODE_TX_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_TX_EN_S, WUFEI_TDM_MODE_TX_EN_W)
#define WUFEI_TDM_MODE_TX_EN_M \
        WUFEI_MASK(WUFEI_TDM_MODE_TX_EN_S, WUFEI_TDM_MODE_TX_EN_W)

/*requests assertion to FM in Rx direction - active high*/
#define WUFEI_TDM_MODE_RX_EN_S (1)
#define WUFEI_TDM_MODE_RX_EN_W (1)
#define WUFEI_TDM_MODE_RX_EN_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_RX_EN_S)
#define WUFEI_TDM_MODE_RX_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_RX_EN_S, WUFEI_TDM_MODE_RX_EN_W)
#define WUFEI_TDM_MODE_RX_EN_M \
        WUFEI_MASK(WUFEI_TDM_MODE_RX_EN_S, WUFEI_TDM_MODE_RX_EN_W)

#endif /* WUFEI_HW_TDM_H*/
