/*****************************************************************************
 * (C) Copyright 2000-2006, Wintegra. All rights reserved.
 * WINTEGRA CONFIDENTIAL PROPRIETARY
 * Contains Confidential Proprietary information of Wintegra.
 * Reverse engineering is prohibited.
 * The copyright notice does not imply publication.
 ****************************************************************************/

/*****************************************************************************
 *
 * File: wufei_hw_gen_regs.h
 *
 * Purpose: the general registers definition for the UFE2+ FPGA
 *
 ****************************************************************************/

#ifndef WUFEI_HW_GEN_REGS_H
#define WUFEI_HW_GEN_REGS_H

#ifndef WUFE_TYPES_H
#include "wufe_types.h"
#endif

#ifndef WUFEI_HW_TYPES_H
#include "wufei_hw_types.h"
#endif

typedef struct
{
   WUFEI_reg_space release_id;
   WUFEI_reg_space secondary_release_id;
   WUFEI_reg_space reserved1[2];
   WUFEI_reg_space build_number;
   WUFEI_reg_space reserved2[11];
}WUFEI_hw_gen_regs_release;

typedef struct
{
   WUFEI_reg_space sys_config;
   WUFEI_reg_space reserved1[7];
}WUFEI_hw_gen_regs_sys_config;

typedef struct
{
   WUFEI_reg_space core_config;
   WUFEI_reg_space reserved1[7];
}WUFEI_hw_gen_regs_core_config;

typedef struct
{
   WUFEI_reg_space liu_config;
   WUFEI_reg_space reserved1[7];
}WUFEI_hw_gen_regs_liu_config;

typedef struct
{
   WUFEI_reg_space global_int;
   WUFEI_reg_space global_mask_int;
   WUFEI_reg_space reserved1[6];
}WUFEI_hw_gen_regs_global_int;

typedef struct
{
   WUFEI_hw_gen_regs_release release;
   WUFEI_hw_gen_regs_sys_config sys_config;
   WUFEI_hw_gen_regs_core_config core0;
   WUFEI_hw_gen_regs_core_config core1;
   WUFEI_hw_gen_regs_liu_config liu;
   WUFEI_hw_gen_regs_global_int interrupt;
   WUFEI_reg_space reserved[0x7c8];
}WUFEI_hw_gen_regs;


/************************************/
/* Release ID register structure    */
/************************************/
#define WUFEI_UFE_RELEASE_ID_S (0)
#define WUFEI_UFE_RELEASE_ID_W (16)
#define WUFEI_UFE_RELEASE_ID_F(v) WUFEI_FIELD(v, WUFEI_UFE_RELEASE_ID_S)
#define WUFEI_UFE_RELEASE_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_RELEASE_ID_S, WUFEI_UFE_RELEASE_ID_W)
#define WUFEI_UFE_RELEASE_ID_M \
        WUFEI_MASK(WUFEI_UFE_RELEASE_ID_S, WUFEI_UFE_RELEASE_ID_W)

/********************************************/
/* Secondary Release ID register structure  */
/********************************************/
#define WUFEI_UFE_SECONDARY_RELEASE_ID_S (0)
#define WUFEI_UFE_SECONDARY_RELEASE_ID_W (16)
#define WUFEI_UFE_SECONDARY_RELEASE_ID_F(v) WUFEI_FIELD(v, WUFEI_UFE_SECONDARY_RELEASE_ID_S)
#define WUFEI_UFE_SECONDARY_RELEASE_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_SECONDARY_RELEASE_ID_S, WUFEI_UFE_SECONDARY_RELEASE_ID_W)
#define WUFEI_UFE_SECONDARY_RELEASE_ID_M \
        WUFEI_MASK(WUFEI_UFE_SECONDARY_RELEASE_ID_S, WUFEI_UFE_SECONDARY_RELEASE_ID_W)

/***************************************/
/* Build number register structure     */
/***************************************/
#define WUFEI_UFE_BUILD_NUM_S (0)
#define WUFEI_UFE_BUILD_NUM_W (16)
#define WUFEI_UFE_BUILD_NUM_F(v) WUFEI_FIELD(v, WUFEI_UFE_BUILD_NUM_S)
#define WUFEI_UFE_BUILD_NUM_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_BUILD_NUM_S, WUFEI_UFE_BUILD_NUM_W)
#define WUFEI_UFE_BUILD_NUM_M \
        WUFEI_MASK(WUFEI_UFE_BUILD_NUM_S, WUFEI_UFE_BUILD_NUM_W)

/********************************************/
/* General Configuration register structure */
/********************************************/
#define WUFEI_UFE_LIU_MODE_S (0)
#define WUFEI_UFE_LIU_MODE_W (2)
#define WUFEI_UFE_LIU_MODE_F(v) WUFEI_FIELD(v, WUFEI_UFE_LIU_MODE_S)
#define WUFEI_UFE_LIU_MODE_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_LIU_MODE_S, WUFEI_UFE_LIU_MODE_W)
#define WUFEI_UFE_LIU_MODE_M \
        WUFEI_MASK(WUFEI_UFE_LIU_MODE_S, WUFEI_UFE_LIU_MODE_W)

#define WUFEI_UFE_EMPHY_SETUP_MODE_S (2)
#define WUFEI_UFE_EMPHY_SETUP_MODE_W (1)
#define WUFEI_UFE_EMPHY_SETUP_MODE_F(v) WUFEI_FIELD(v, WUFEI_UFE_EMPHY_SETUP_MODE_S)
#define WUFEI_UFE_EMPHY_SETUP_MODE_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_EMPHY_SETUP_MODE_S, WUFEI_UFE_EMPHY_SETUP_MODE_W)
#define WUFEI_UFE_EMPHY_SETUP_MODE_M \
        WUFEI_MASK(WUFEI_UFE_EMPHY_SETUP_MODE_S, WUFEI_UFE_EMPHY_SETUP_MODE_W)

#define WUFEI_UFE_CLK_REC_RX_ENABLE_S (3)
#define WUFEI_UFE_CLK_REC_RX_ENABLE_W (1)
#define WUFEI_UFE_CLK_REC_RX_ENABLE_F(v) WUFEI_FIELD(v, WUFEI_UFE_CLK_REC_RX_ENABLE_S)
#define WUFEI_UFE_CLK_REC_RX_ENABLE_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_CLK_REC_RX_ENABLE_S, WUFEI_UFE_CLK_REC_RX_ENABLE_W)
#define WUFEI_UFE_CLK_REC_RX_ENABLE_M \
        WUFEI_MASK(WUFEI_UFE_CLK_REC_RX_ENABLE_S, WUFEI_UFE_CLK_REC_RX_ENABLE_W)

#define WUFEI_UFE_CLK_REC_TX_ENABLE_S (4)
#define WUFEI_UFE_CLK_REC_TX_ENABLE_W (1)
#define WUFEI_UFE_CLK_REC_TX_ENABLE_F(v) WUFEI_FIELD(v, WUFEI_UFE_CLK_REC_TX_ENABLE_S)
#define WUFEI_UFE_CLK_REC_TX_ENABLE_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_CLK_REC_TX_ENABLE_S, WUFEI_UFE_CLK_REC_TX_ENABLE_W)
#define WUFEI_UFE_CLK_REC_TX_ENABLE_M \
        WUFEI_MASK(WUFEI_UFE_CLK_REC_TX_ENABLE_S, WUFEI_UFE_CLK_REC_TX_ENABLE_W)

#define WUFEI_UFE_BANDWIDTH_S (14)
#define WUFEI_UFE_BANDWIDTH_W (2)
#define WUFEI_UFE_BANDWIDTH_F(v) WUFEI_FIELD(v, WUFEI_UFE_BANDWIDTH_S)
#define WUFEI_UFE_BANDWIDTH_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_BANDWIDTH_S, WUFEI_UFE_BANDWIDTH_W)
#define WUFEI_UFE_BANDWIDTH_M \
        WUFEI_MASK(WUFEI_UFE_BANDWIDTH_S, WUFEI_UFE_BANDWIDTH_W)

#define WUFEI_GLOBAL_CFG_BANDWIDTH_STM_4 0
#define WUFEI_GLOBAL_CFG_BANDWIDTH_STM_2 1
#define WUFEI_GLOBAL_CFG_BANDWIDTH_STM_1 2

/*********************************************/
/* UFE core configuration register structure */
/*********************************************/
#define WUFEI_UFE_CORE_INT_ZBT_S (15)
#define WUFEI_UFE_CORE_INT_ZBT_W (1)
#define WUFEI_UFE_CORE_INT_ZBT_F(v) WUFEI_FIELD(v, WUFEI_UFE_CORE_INT_ZBT_S)
#define WUFEI_UFE_CORE_INT_ZBT_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_CORE_INT_ZBT_S, WUFEI_UFE_CORE_INT_ZBT_W)
#define WUFEI_UFE_CORE_INT_ZBT_M \
        WUFEI_MASK(WUFEI_UFE_CORE_INT_ZBT_S, WUFEI_UFE_CORE_INT_ZBT_W)

#define WUFEI_UFE_CORE_ZBT_SIZE_S (12)
#define WUFEI_UFE_CORE_ZBT_SIZE_W (3)
#define WUFEI_UFE_CORE_ZBT_SIZE_F(v) WUFEI_FIELD(v, WUFEI_UFE_CORE_ZBT_SIZE_S)
#define WUFEI_UFE_CORE_ZBT_SIZE_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_CORE_ZBT_SIZE_S, WUFEI_UFE_CORE_ZBT_SIZE_W)
#define WUFEI_UFE_CORE_ZBT_SIZE_M \
        WUFEI_MASK(WUFEI_UFE_CORE_ZBT_SIZE_S, WUFEI_UFE_CORE_ZBT_SIZE_W)

#define WUFEI_UFE_CORE_ENABLED_S (11)
#define WUFEI_UFE_CORE_ENABLED_W (1)
#define WUFEI_UFE_CORE_ENABLED_F(v) WUFEI_FIELD(v, WUFEI_UFE_CORE_ENABLED_S)
#define WUFEI_UFE_CORE_ENABLED_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_CORE_ENABLED_S, WUFEI_UFE_CORE_ENABLED_W)
#define WUFEI_UFE_CORE_ENABLED_M \
        WUFEI_MASK(WUFEI_UFE_CORE_ENABLED_S, WUFEI_UFE_CORE_ENABLED_W)

#define WUFEI_UFE_TDM_SYS_LOOP_INC_S (10)
#define WUFEI_UFE_TDM_SYS_LOOP_INC_W (1)
#define WUFEI_UFE_TDM_SYS_LOOP_INC_F(v) WUFEI_FIELD(v, WUFEI_UFE_TDM_SYS_LOOP_INC_S)
#define WUFEI_UFE_TDM_SYS_LOOP_INC_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_TDM_SYS_LOOP_INC_S, WUFEI_UFE_TDM_SYS_LOOP_INC_W)
#define WUFEI_UFE_TDM_SYS_LOOP_INC_M \
        WUFEI_MASK(WUFEI_UFE_TDM_SYS_LOOP_INC_S, WUFEI_UFE_TDM_SYS_LOOP_INC_W)

#define WUFEI_UFE_TDM_LINE_LOOP_INC_S (9)
#define WUFEI_UFE_TDM_LINE_LOOP_INC_W (1)
#define WUFEI_UFE_TDM_LINE_LOOP_INC_F(v) WUFEI_FIELD(v, WUFEI_UFE_TDM_LINE_LOOP_INC_S)
#define WUFEI_UFE_TDM_LINE_LOOP_INC_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_TDM_LINE_LOOP_INC_S, WUFEI_UFE_TDM_LINE_LOOP_INC_W)
#define WUFEI_UFE_TDM_LINE_LOOP_INC_M \
        WUFEI_MASK(WUFEI_UFE_TDM_LINE_LOOP_INC_S, WUFEI_UFE_TDM_LINE_LOOP_INC_W)

#define WUFEI_GEN_CFG_SYS_REG_MACHINE_S (0)
#define WUFEI_GEN_CFG_SYS_REG_MACHINE_W (3)
#define WUFEI_GEN_CFG_SYS_REG_MACHINE_V(f) \
   WUFEI_VALUE(f, WUFEI_GEN_CFG_SYS_REG_MACHINE_S, WUFEI_GEN_CFG_SYS_REG_MACHINE_W)

#define WUFEI_GEN_CFG_SYS_REG_MACHINE_TRANS 0x1
#define WUFEI_GEN_CFG_SYS_REG_MACHINE_ATM   0x2
#define WUFEI_GEN_CFG_SYS_REG_MACHINE_HDLC  0x4

/****************************************/
/* LIU Configuration register structure */
/****************************************/

#define WUFEI_UFE_SBI_MODE_S (14)
#define WUFEI_UFE_SBI_MODE_W (2)
#define WUFEI_UFE_SBI_MODE_F(v) WUFEI_FIELD(v, WUFEI_UFE_SBI_MODE_S)
#define WUFEI_UFE_SBI_MODE_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_SBI_MODE_S, WUFEI_UFE_SBI_MODE_W)
#define WUFEI_UFE_SBI_MODE_M \
        WUFEI_MASK(WUFEI_UFE_SBI_MODE_S, WUFEI_UFE_SBI_MODE_W)

#define WUFEI_UFE_LIU_MODE_CORE1_S (14)
#define WUFEI_UFE_LIU_MODE_CORE1_W (2)
#define WUFEI_UFE_LIU_MODE_CORE1_F(v) WUFEI_FIELD(v, WUFEI_UFE_LIU_MODE_CORE1_S)
#define WUFEI_UFE_LIU_MODE_CORE1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_LIU_MODE_CORE1_S, WUFEI_UFE_LIU_MODE_CORE1_W)
#define WUFEI_UFE_LIU_MODE_CORE1_M \
        WUFEI_MASK(WUFEI_UFE_LIU_MODE_CORE1_S, WUFEI_UFE_LIU_MODE_CORE1_W)

#define WUFEI_UFE_CAD_UNIT_NUM_CORE1_S (8)
#define WUFEI_UFE_CAD_UNIT_NUM_CORE1_W (6)
#define WUFEI_UFE_CAD_UNIT_NUM_CORE1_F(v) WUFEI_FIELD(v, WUFEI_UFE_CAD_UNIT_NUM_CORE1_S)
#define WUFEI_UFE_CAD_UNIT_NUM_CORE1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_CAD_UNIT_NUM_CORE1_S, WUFEI_UFE_CAD_UNIT_NUM_CORE1_W)
#define WUFEI_UFE_CAD_UNIT_NUM_CORE1_M \
        WUFEI_MASK(WUFEI_UFE_CAD_UNIT_NUM_CORE1_S, WUFEI_UFE_CAD_UNIT_NUM_CORE1_W)

#define WUFEI_UFE_LIU_MODE_CORE0_S (6)
#define WUFEI_UFE_LIU_MODE_CORE0_W (2)
#define WUFEI_UFE_LIU_MODE_CORE0_F(v) WUFEI_FIELD(v, WUFEI_UFE_LIU_MODE_CORE0_S)
#define WUFEI_UFE_LIU_MODE_CORE0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_LIU_MODE_CORE0_S, WUFEI_UFE_LIU_MODE_CORE0_W)
#define WUFEI_UFE_LIU_MODE_CORE0_M \
        WUFEI_MASK(WUFEI_UFE_LIU_MODE_CORE0_S, WUFEI_UFE_LIU_MODE_CORE0_W)

#define WUFEI_UFE_CAD_UNIT_NUM_CORE0_S (0)
#define WUFEI_UFE_CAD_UNIT_NUM_CORE0_W (6)
#define WUFEI_UFE_CAD_UNIT_NUM_CORE0_F(v) WUFEI_FIELD(v, WUFEI_UFE_CAD_UNIT_NUM_CORE0_S)
#define WUFEI_UFE_CAD_UNIT_NUM_CORE0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_CAD_UNIT_NUM_CORE0_S, WUFEI_UFE_CAD_UNIT_NUM_CORE0_W)
#define WUFEI_UFE_CAD_UNIT_NUM_CORE0_M \
        WUFEI_MASK(WUFEI_UFE_CAD_UNIT_NUM_CORE0_S, WUFEI_UFE_CAD_UNIT_NUM_CORE0_W)

/***************************************/
/* Global interrupt register structure */
/***************************************/
#define WUFEI_UFE_GLOBAL_INT_CORE0_S (0)
#define WUFEI_UFE_GLOBAL_INT_CORE0_W (1)
#define WUFEI_UFE_GLOBAL_INT_CORE0_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_CORE0_S)
#define WUFEI_UFE_GLOBAL_INT_CORE0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_CORE0_S, WUFEI_UFE_GLOBAL_INT_CORE0_W)
#define WUFEI_UFE_GLOBAL_INT_CORE0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_CORE0_S, WUFEI_UFE_GLOBAL_INT_CORE0_W)

#define WUFEI_UFE_GLOBAL_INT_CORE1_S (1)
#define WUFEI_UFE_GLOBAL_INT_CORE1_W (1)
#define WUFEI_UFE_GLOBAL_INT_CORE1_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_CORE1_S)
#define WUFEI_UFE_GLOBAL_INT_CORE1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_CORE1_S, WUFEI_UFE_GLOBAL_INT_CORE1_W)
#define WUFEI_UFE_GLOBAL_INT_CORE1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_CORE1_S, WUFEI_UFE_GLOBAL_INT_CORE1_W)

#define WUFEI_UFE_GLOBAL_INT_EMPHY_CORE0_S (2)
#define WUFEI_UFE_GLOBAL_INT_EMPHY_CORE0_W (1)
#define WUFEI_UFE_GLOBAL_INT_EMPHY_CORE0_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_EMPHY_CORE0_S)
#define WUFEI_UFE_GLOBAL_INT_EMPHY_CORE0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_EMPHY_CORE0_S, WUFEI_UFE_GLOBAL_INT_EMPHY_CORE0_W)
#define WUFEI_UFE_GLOBAL_INT_EMPHY_CORE0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_EMPHY_CORE0_S, WUFEI_UFE_GLOBAL_INT_EMPHY_CORE0_W)

#define WUFEI_UFE_GLOBAL_INT_EMPHY_CORE1_S (3)
#define WUFEI_UFE_GLOBAL_INT_EMPHY_CORE1_W (1)
#define WUFEI_UFE_GLOBAL_INT_EMPHY_CORE1_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_EMPHY_CORE1_S)
#define WUFEI_UFE_GLOBAL_INT_EMPHY_CORE1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_EMPHY_CORE1_S, WUFEI_UFE_GLOBAL_INT_EMPHY_CORE1_W)
#define WUFEI_UFE_GLOBAL_INT_EMPHY_CORE1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_EMPHY_CORE1_S, WUFEI_UFE_GLOBAL_INT_EMPHY_CORE1_W)

#define WUFEI_UFE_GLOBAL_INT_LIU_S (4)
#define WUFEI_UFE_GLOBAL_INT_LIU_W (1)
#define WUFEI_UFE_GLOBAL_INT_LIU_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_LIU_S)
#define WUFEI_UFE_GLOBAL_INT_LIU_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_LIU_S, WUFEI_UFE_GLOBAL_INT_LIU_W)
#define WUFEI_UFE_GLOBAL_INT_LIU_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_LIU_S, WUFEI_UFE_GLOBAL_INT_LIU_W)

#define WUFEI_UFE_GLOBAL_INT_CR_S (5)
#define WUFEI_UFE_GLOBAL_INT_CR_W (1)
#define WUFEI_UFE_GLOBAL_INT_CR_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_CR_S)
#define WUFEI_UFE_GLOBAL_INT_CR_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_CR_S, WUFEI_UFE_GLOBAL_INT_CR_W)
#define WUFEI_UFE_GLOBAL_INT_CR_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_CR_S, WUFEI_UFE_GLOBAL_INT_CR_W)

/********************************************/
/* Global mask interrupt register structure */
/********************************************/
#define WUFEI_UFE_GLOBAL_MASK_INT_CORE0_S (0)
#define WUFEI_UFE_GLOBAL_MASK_INT_CORE0_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_CORE0_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_CORE0_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_CORE0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_CORE0_S, WUFEI_UFE_GLOBAL_MASK_INT_CORE0_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_CORE0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_CORE0_S, WUFEI_UFE_GLOBAL_MASK_INT_CORE0_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_CORE1_S (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_CORE1_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_CORE1_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_CORE1_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_CORE1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_CORE1_S, WUFEI_UFE_GLOBAL_MASK_INT_CORE1_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_CORE1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_CORE1_S, WUFEI_UFE_GLOBAL_MASK_INT_CORE1_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE0_S (2)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE0_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE0_F(v) \
        WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE0_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE0_S,\
        WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE0_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE0_S,\
        WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE0_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE1_S (3)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE1_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE1_F(v) \
        WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE1_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE1_S,\
        WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE1_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE1_S,\
        WUFEI_UFE_GLOBAL_MASK_INT_EMPHY_CORE1_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_LIU_S (4)
#define WUFEI_UFE_GLOBAL_MASK_INT_LIU_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_LIU_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_LIU_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_LIU_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_LIU_S, WUFEI_UFE_GLOBAL_MASK_INT_LIU_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_LIU_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_LIU_S, WUFEI_UFE_GLOBAL_MASK_INT_LIU_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_CR_S (5)
#define WUFEI_UFE_GLOBAL_MASK_INT_CR_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_CR_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_CR_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_CR_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_CR_S, WUFEI_UFE_GLOBAL_MASK_INT_CR_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_CR_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_CR_S, WUFEI_UFE_GLOBAL_MASK_INT_CR_W)

#endif /*WUFEI_HW_GEN_REGS_H*/
