#
#                              Makefile.UNX
#
# Makes dos2unix and unix2dos under Unix
#

CFLAGS = -O

all          : dos2unix unix2dos

dos2unix     : dos2unix.c
	gcc $(CFLAGS) -o dos2ux dos2unix.c

unix2dos     : unix2dos.c
	gcc $(CFLAGS) -o ux2dos unix2dos.c


