#!/bin/bash
surfix=''
echo $surfix
rm ./bin/*
pwd | grep "wilbur"
if test $? -eq 0  
then
   echo "this is in WILBUR code"
   surfix='wilbur'
fi


hn=`hostname`
echo hostname=[$hn]

if [ $hn = "ubuntu" ]; then
	filepath=/mnt/hgfs/Temp/
else
	filepath=/tftpboot/
fi 

filename=pwe3_satop_cesop_demo_${surfix}.exe

# exit

echo touch pwe3_satop_cesop_demo.c 
touch *.c 

echo =========================================
echo make WDDS_DIR=../ \
WDDI_TARGET_NAME=mips_winmon \
WDDI_BOARD_NAME=wds \
WDDI_HOST=linux \
WDDI_HW_DEVICE=winpath3 \
UFE_DIR=../ufe \
UFE=ufe412 \
FRAMER=flexmux
echo =========================================

make WDDS_DIR=../ \
WDDI_TARGET_NAME=mips_winmon \
WDDI_BOARD_NAME=wds \
WDDI_HOST=linux \
WDDI_HW_DEVICE=winpath3 \
UFE_DIR=../ufe \
UFE=ufe412 \
FRAMER=flexmux \
&& rsync ./bin/pwe3_satop_cesop_demo.exe ${filepath}${filename}
echo rsync ./bin/pwe3_satop_cesop_demo.exe ${filepath}${filename} complete !
