#!/bin/bash
ctags -R
cd bin
rm -rf *
cd ..
make TEST=EnetDemo
# copy_to_tftpboot.sh
# cp bin/EnetDemo /tftpboot/enetdemo_linux_431.exe
# cd bin
# mv EnetDemo EnetDemo_lin.exe 
# up EnetDemo_lin.exe bin

