/*****************************************************************************
 * (C) Copyright 2000-2006, Wintegra. All rights reserved.
 * WINTEGRA CONFIDENTIAL PROPRIETARY
 * Contains Confidential Proprietary information of Wintegra.
 * Reverse engineering is prohibited.
 * The copyright notice does not imply publication.
 ****************************************************************************/

/*****************************************************************************
 *
 * File: wufei_hw_machine.h
 *
 * Purpose: the UFE MACHINE  macro and structures
 *
 ****************************************************************************/
#ifndef WUFEI_HW_MACHINE_H
#define WUFEI_HW_MACHINE_H

#ifndef WUFE_SYSTEM_H
#include "wufe_system.h"
#endif

#ifndef WUFEI_HW_TYPES_H
#include "wufei_hw_types.h"
#endif

#define WUFEI_HW_MACHINE_TX_START_THRESH_OPTIONS 4

typedef struct
{
      WUFEI_reg_space machine_ind_low; /*MACHINE indirect address low*/
      WUFEI_reg_space machine_ind_high; /*MACHINE indirect address high*/
      WUFEI_reg_space machine_ind_cmd; /*MACHINE indirect address cmd*/
      WUFEI_reg_space machine_ind_data; /*MACHINE indirect address data*/
      WUFEI_reg_space reserved1[4]; /*Reserved for future enhancements*/
      WUFEI_reg_space machine_rx_interrupt; /*MACHINE interrupt*/
      WUFEI_reg_space machine_rx_interrupt_mask; /*MACHINE interrupt mask*/
      WUFEI_reg_space machine_tx_interrupt; /*MACHINE interrupt*/
      WUFEI_reg_space machine_tx_interrupt_mask; /*MACHINE interrupt mask*/
      WUFEI_reg_space machine_rx_int_port_id; /*MACHINE interrupt port id*/
      WUFEI_reg_space machine_tx_int_port_id; /*MACHINE interrupt port id*/
      WUFEI_reg_space reserved2[2];
      WUFEI_reg_space machine_tx_start_tx_threshold[WUFEI_HW_MACHINE_TX_START_THRESH_OPTIONS];
}WUFEI_hw_machine;

#define MAC_NUM_REGS_PER_SPT 8     /* num of registers in TSPT/RSPT */
#define MAC_NUM_REGS_PER_PT 0x10
#define MAC_NUM_ACTUAL_REGS_PER_PT 10
#define CES_MAC_SLOTS_REG_OFFSET_RX 2
#define CES_MAC_SLOTS_REG_OFFSET_TX 3
#define MAC_ENB_REG_OFFSET 8
#define CES_MAC_CAS_TABLE_OFFSET 0x10
#define CES_MAC_NSPP_OFFSET_REGS 8

#define MAC_CES_UNDERRUN_OFFSET 0
#define MAC_ATM_UNDERRUN_OFFSET 2
#define MAC_ATM_SYNC_STATE_OFFSET 2
#define MAC_HDLC_UNDERRUN_OFFSET 3

#define CES_MAC_NUM_REGS_PER_CAS_TABLE 8
#define CES_CAS_TABLE_INITIAL_VALUE 0x3333
#define CES_MAC_NOT_RECONFIGURE 0xffff
#define WUFEI_MAX_NUM_OF_SLOTS 32

#define WUFEI_PHY_MODE_TRANS    0x0
#define WUFEI_PHY_MODE_ATM      0x1
#define WUFEI_PHY_MODE_HDLC_BIT 0x2
#define WUFEI_PHY_MODE_POS      0x3
#define WUFEI_PHY_MODE_GFP      0x4

#define WUFEI_HW_ATM_RX_CELL_DELINEATION_BYTE_RESOLUTION 0
#define WUFEI_HW_ATM_RX_CELL_DELINEATION_NIBBLE_RESOLUTION 1

#define WUFEI_HW_MACHINE_TX_START_THRESH_ATM_OC3 10
#define WUFEI_HW_MACHINE_TX_START_THRESH_ATM_OC12 10
#define WUFEI_HW_MACHINE_TX_START_THRESH_POS_OC3 32
#define WUFEI_HW_MACHINE_TX_START_THRESH_POS_OC12 32

/* CES MACHINE */

#define WUFEI_CES_RX_MODE_DATA_U_SIZE_S (8)
#define WUFEI_CES_RX_MODE_DATA_U_SIZE_W (8)
#define WUFEI_CES_RX_MODE_DATA_U_SIZE_F(v) WUFEI_FIELD(v, WUFEI_CES_RX_MODE_DATA_U_SIZE_S)
#define WUFEI_CES_RX_MODE_DATA_U_SIZE_V(f) \
        WUFEI_VALUE(f, WUFEI_CES_RX_MODE_DATA_U_SIZE_S, WUFEI_CES_RX_MODE_DATA_U_SIZE_W)
#define WUFEI_CES_RX_MODE_DATA_U_SIZE_M \
        WUFEI_MASK(WUFEI_CES_RX_MODE_DATA_U_SIZE_S, WUFEI_CES_RX_MODE_DATA_U_SIZE_W)

#define WUFEI_CES_RX_MODE_NSPP_S (0)
#define WUFEI_CES_RX_MODE_NSPP_W (5)
#define WUFEI_CES_RX_MODE_NSPP_F(v) WUFEI_FIELD(v, WUFEI_CES_RX_MODE_NSPP_S)
#define WUFEI_CES_RX_MODE_NSPP_V(f) \
        WUFEI_VALUE(f, WUFEI_CES_RX_MODE_NSPP_S, WUFEI_CES_RX_MODE_NSPP_W)
#define WUFEI_CES_RX_MODE_NSPP_M \
        WUFEI_MASK(WUFEI_CES_RX_MODE_NSPP_S, WUFEI_CES_RX_MODE_NSPP_W)

#define WUFEI_CES_TX_MODE_NSPP_S (0)
#define WUFEI_CES_TX_MODE_NSPP_W (5)
#define WUFEI_CES_TX_MODE_NSPP_F(v) WUFEI_FIELD(v, WUFEI_CES_TX_MODE_NSPP_S)
#define WUFEI_CES_TX_MODE_NSPP_V(f) \
        WUFEI_VALUE(f, WUFEI_CES_TX_MODE_NSPP_S, WUFEI_CES_TX_MODE_NSPP_W)
#define WUFEI_CES_TX_MODE_NSPP_M \
        WUFEI_MASK(WUFEI_CES_TX_MODE_NSPP_S, WUFEI_CES_TX_MODE_NSPP_W)

#define WUFEI_CES_RX_MODE_EN_S (11)
#define WUFEI_CES_RX_MODE_EN_W (1)
#define WUFEI_CES_RX_MODE_EN_F(v) WUFEI_FIELD(v, WUFEI_CES_RX_MODE_EN_S)
#define WUFEI_CES_RX_MODE_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_CES_RX_MODE_EN_S, WUFEI_CES_RX_MODE_EN_W)
#define WUFEI_CES_RX_MODE_EN_M \
        WUFEI_MASK(WUFEI_CES_RX_MODE_EN_S, WUFEI_CES_RX_MODE_EN_W)

#define WUFEI_CES_TX_MODE_EN_S (11)
#define WUFEI_CES_TX_MODE_EN_W (1)
#define WUFEI_CES_TX_MODE_EN_F(v) WUFEI_FIELD(v, WUFEI_CES_TX_MODE_EN_S)
#define WUFEI_CES_TX_MODE_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_CES_TX_MODE_EN_S, WUFEI_CES_TX_MODE_EN_W)
#define WUFEI_CES_TX_MODE_EN_M \
        WUFEI_MASK(WUFEI_CES_TX_MODE_EN_S, WUFEI_CES_TX_MODE_EN_W)

#define WUFEI_CES_RX_MODE_TYPE_S (12)
#define WUFEI_CES_RX_MODE_TYPE_W (4)
#define WUFEI_CES_RX_MODE_TYPE_F(v) WUFEI_FIELD(v, WUFEI_CES_RX_MODE_TYPE_S)
#define WUFEI_CES_RX_MODE_TYPE_V(f) \
        WUFEI_VALUE(f, WUFEI_CES_RX_MODE_TYPE_S, WUFEI_CES_RX_MODE_TYPE_W)
#define WUFEI_CES_RX_MODE_TYPE_M \
        WUFEI_MASK(WUFEI_CES_RX_MODE_TYPE_S, WUFEI_CES_RX_MODE_TYPE_W)

#define WUFEI_CES_TX_MODE_TYPE_S (12)
#define WUFEI_CES_TX_MODE_TYPE_W (4)
#define WUFEI_CES_TX_MODE_TYPE_F(v) WUFEI_FIELD(v, WUFEI_CES_TX_MODE_TYPE_S)
#define WUFEI_CES_TX_MODE_TYPE_V(f) \
        WUFEI_VALUE(f, WUFEI_CES_TX_MODE_TYPE_S, WUFEI_CES_TX_MODE_TYPE_W)
#define WUFEI_CES_TX_MODE_TYPE_M \
        WUFEI_MASK(WUFEI_CES_TX_MODE_TYPE_S, WUFEI_CES_TX_MODE_TYPE_W)

#define WUFEI_CES_TX_UNDERRUN_S (2)
#define WUFEI_CES_TX_UNDERRUN_W (2)
#define WUFEI_CES_TX_UNDERRUN_F(v) WUFEI_FIELD(v, WUFEI_CES_TX_UNDERRUN_S)
#define WUFEI_CES_TX_UNDERRUN_V(f) \
        WUFEI_VALUE(f, WUFEI_CES_TX_UNDERRUN_S, WUFEI_CES_TX_UNDERRUN_W)
#define WUFEI_CES_TX_UNDERRUN_M \
        WUFEI_MASK(WUFEI_CES_TX_UNDERRUN_S, WUFEI_CES_TX_UNDERRUN_W)

/* HDLC MACHINE */

#define WUFEI_HDLC_RX_MODE_EN_S (11)
#define WUFEI_HDLC_RX_MODE_EN_W (1)
#define WUFEI_HDLC_RX_MODE_EN_F(v) WUFEI_FIELD(v, WUFEI_HDLC_RX_MODE_EN_S)
#define WUFEI_HDLC_RX_MODE_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_HDLC_RX_MODE_EN_S, WUFEI_HDLC_RX_MODE_EN_W)
#define WUFEI_HDLC_RX_MODE_EN_M \
        WUFEI_MASK(WUFEI_HDLC_RX_MODE_EN_S, WUFEI_HDLC_RX_MODE_EN_W)

#define WUFEI_HDLC_TX_MODE_EN_S (11)
#define WUFEI_HDLC_TX_MODE_EN_W (1)
#define WUFEI_HDLC_TX_MODE_EN_F(v) WUFEI_FIELD(v, WUFEI_HDLC_TX_MODE_EN_S)
#define WUFEI_HDLC_TX_MODE_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_HDLC_TX_MODE_EN_S, WUFEI_HDLC_TX_MODE_EN_W)
#define WUFEI_HDLC_TX_MODE_EN_M \
        WUFEI_MASK(WUFEI_HDLC_TX_MODE_EN_S, WUFEI_HDLC_TX_MODE_EN_W)

#define WUFEI_HDLC_TX_UNDERRUN_S (13)
#define WUFEI_HDLC_TX_UNDERRUN_W (1)
#define WUFEI_HDLC_TX_UNDERRUN_F(v) WUFEI_FIELD(v, WUFEI_HDLC_TX_UNDERRUN_S)
#define WUFEI_HDLC_TX_UNDERRUN_V(f) \
        WUFEI_VALUE(f, WUFEI_HDLC_TX_UNDERRUN_S, WUFEI_HDLC_TX_UNDERRUN_W)
#define WUFEI_HDLC_TX_UNDERRUN_M \
        WUFEI_MASK(WUFEI_HDLC_TX_UNDERRUN_S, WUFEI_HDLC_TX_UNDERRUN_W)

#define WUFEI_HDLC_RX_MODE_TYPE_S (12)
#define WUFEI_HDLC_RX_MODE_TYPE_W (4)
#define WUFEI_HDLC_RX_MODE_TYPE_F(v) WUFEI_FIELD(v, WUFEI_HDLC_RX_MODE_TYPE_S)
#define WUFEI_HDLC_RX_MODE_TYPE_V(f) \
        WUFEI_VALUE(f, WUFEI_HDLC_RX_MODE_TYPE_S, WUFEI_HDLC_RX_MODE_TYPE_W)
#define WUFEI_HDLC_RX_MODE_TYPE_M \
        WUFEI_MASK(WUFEI_HDLC_RX_MODE_TYPE_S, WUFEI_HDLC_RX_MODE_TYPE_W)

#define WUFEI_HDLC_TX_MODE_TYPE_S (12)
#define WUFEI_HDLC_TX_MODE_TYPE_W (4)
#define WUFEI_HDLC_TX_MODE_TYPE_F(v) WUFEI_FIELD(v, WUFEI_HDLC_TX_MODE_TYPE_S)
#define WUFEI_HDLC_TX_MODE_TYPE_V(f) \
        WUFEI_VALUE(f, WUFEI_HDLC_TX_MODE_TYPE_S, WUFEI_HDLC_TX_MODE_TYPE_W)
#define WUFEI_HDLC_TX_MODE_TYPE_M \
        WUFEI_MASK(WUFEI_HDLC_TX_MODE_TYPE_S, WUFEI_HDLC_TX_MODE_TYPE_W)

#define WUFEI_HDLC_TX_FCS_S (10)
#define WUFEI_HDLC_TX_FCS_W (1)
#define WUFEI_HDLC_TX_FCS_F(v) WUFEI_FIELD(v, WUFEI_HDLC_TX_FCS_S)
#define WUFEI_HDLC_TX_FCS_V(f) \
        WUFEI_VALUE(f, WUFEI_HDLC_TX_FCS_S, WUFEI_HDLC_TX_FCS_W)
#define WUFEI_HDLC_TX_FCS_M \
        WUFEI_MASK(WUFEI_HDLC_TX_FCS_S, WUFEI_HDLC_TX_FCS_W)

#define WUFEI_HDLC_RX_FCS_S (10)
#define WUFEI_HDLC_RX_FCS_W (1)
#define WUFEI_HDLC_RX_FCS_F(v) WUFEI_FIELD(v, WUFEI_HDLC_RX_FCS_S)
#define WUFEI_HDLC_RX_FCS_V(f) \
        WUFEI_VALUE(f, WUFEI_HDLC_RX_FCS_S, WUFEI_HDLC_RX_FCS_W)
#define WUFEI_HDLC_RX_FCS_M \
        WUFEI_MASK(WUFEI_HDLC_RX_FCS_S, WUFEI_HDLC_RX_FCS_W)

#define WUFEI_HDLC_TX_IDLE_S (9)
#define WUFEI_HDLC_TX_IDLE_W (1)
#define WUFEI_HDLC_TX_IDLE_F(v) WUFEI_FIELD(v, WUFEI_HDLC_TX_IDLE_S)
#define WUFEI_HDLC_TX_IDLE_V(f) \
        WUFEI_VALUE(f, WUFEI_HDLC_TX_IDLE_S, WUFEI_HDLC_TX_IDLE_W)
#define WUFEI_HDLC_TX_IDLE_M \
        WUFEI_MASK(WUFEI_HDLC_TX_IDLE_S, WUFEI_HDLC_TX_IDLE_W)

#define WUFEI_HDLC_TX_NOF_S (5)
#define WUFEI_HDLC_TX_NOF_W (4)
#define WUFEI_HDLC_TX_NOF_F(v) WUFEI_FIELD(v, WUFEI_HDLC_TX_NOF_S)
#define WUFEI_HDLC_TX_NOF_V(f) \
        WUFEI_VALUE(f, WUFEI_HDLC_TX_NOF_S, WUFEI_HDLC_TX_NOF_W)
#define WUFEI_HDLC_TX_NOF_M \
        WUFEI_MASK(WUFEI_HDLC_TX_NOF_S, WUFEI_HDLC_TX_NOF_W)

/* ATM MACHINE */

#define WUFEI_ATM_RX_MODE_TYPE_S (12)
#define WUFEI_ATM_RX_MODE_TYPE_W (4)
#define WUFEI_ATM_RX_MODE_TYPE_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_MODE_TYPE_S)
#define WUFEI_ATM_RX_MODE_TYPE_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_MODE_TYPE_S, WUFEI_ATM_RX_MODE_TYPE_W)
#define WUFEI_ATM_RX_MODE_TYPE_M \
        WUFEI_MASK(WUFEI_ATM_RX_MODE_TYPE_S, WUFEI_ATM_RX_MODE_TYPE_W)

#define WUFEI_ATM_RX_DELTA_S (12)
#define WUFEI_ATM_RX_DELTA_W (4)
#define WUFEI_ATM_RX_DELTA_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_DELTA_S)
#define WUFEI_ATM_RX_DELTA_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_DELTA_S, WUFEI_ATM_RX_DELTA_W)
#define WUFEI_ATM_RX_DELTA_M \
        WUFEI_MASK(WUFEI_ATM_RX_DELTA_S, WUFEI_ATM_RX_DELTA_W)

#define WUFEI_ATM_RX_ALPHA_S (8)
#define WUFEI_ATM_RX_ALPHA_W (4)
#define WUFEI_ATM_RX_ALPHA_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_ALPHA_S)
#define WUFEI_ATM_RX_ALPHA_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_ALPHA_S, WUFEI_ATM_RX_ALPHA_W)
#define WUFEI_ATM_RX_ALPHA_M \
        WUFEI_MASK(WUFEI_ATM_RX_ALPHA_S, WUFEI_ATM_RX_ALPHA_W)

#define WUFEI_ATM_RX_MODE_EN_S (11)
#define WUFEI_ATM_RX_MODE_EN_W (1)
#define WUFEI_ATM_RX_MODE_EN_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_MODE_EN_S)
#define WUFEI_ATM_RX_MODE_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_MODE_EN_S, WUFEI_ATM_RX_MODE_EN_W)
#define WUFEI_ATM_RX_MODE_EN_M \
        WUFEI_MASK(WUFEI_ATM_RX_MODE_EN_S, WUFEI_ATM_RX_MODE_EN_W)

#define WUFEI_ATM_RX_DESCRAMBLER_S (10)
#define WUFEI_ATM_RX_DESCRAMBLER_W (1)
#define WUFEI_ATM_RX_DESCRAMBLER_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_DESCRAMBLER_S)
#define WUFEI_ATM_RX_DESCRAMBLER_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_DESCRAMBLER_S, WUFEI_ATM_RX_DESCRAMBLER_W)
#define WUFEI_ATM_RX_DESCRAMBLER_M \
        WUFEI_MASK(WUFEI_ATM_RX_DESCRAMBLER_S, WUFEI_ATM_RX_DESCRAMBLER_W)

#define WUFEI_ATM_RX_COSET_S (9)
#define WUFEI_ATM_RX_COSET_W (1)
#define WUFEI_ATM_RX_COSET_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_COSET_S)
#define WUFEI_ATM_RX_COSET_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_COSET_S, WUFEI_ATM_RX_COSET_W)
#define WUFEI_ATM_RX_COSET_M \
        WUFEI_MASK(WUFEI_ATM_RX_COSET_S, WUFEI_ATM_RX_COSET_W)

#define WUFEI_ATM_RX_IDLE_CELL_S (8)
#define WUFEI_ATM_RX_IDLE_CELL_W (1)
#define WUFEI_ATM_RX_IDLE_CELL_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_IDLE_CELL_S)
#define WUFEI_ATM_RX_IDLE_CELL_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_IDLE_CELL_S, WUFEI_ATM_RX_IDLE_CELL_W)
#define WUFEI_ATM_RX_IDLE_CELL_M \
        WUFEI_MASK(WUFEI_ATM_RX_IDLE_CELL_S, WUFEI_ATM_RX_IDLE_CELL_W)

#define WUFEI_ATM_RX_UCD_S (7)
#define WUFEI_ATM_RX_UCD_W (1)
#define WUFEI_ATM_RX_UCD_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_UCD_S)
#define WUFEI_ATM_RX_UCD_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_UCD_S, WUFEI_ATM_RX_UCD_W)
#define WUFEI_ATM_RX_UCD_M \
        WUFEI_MASK(WUFEI_ATM_RX_UCD_S, WUFEI_ATM_RX_UCD_W)

#define WUFEI_ATM_RX_HECD_S (6)
#define WUFEI_ATM_RX_HECD_W (1)
#define WUFEI_ATM_RX_HECD_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_HECD_S)
#define WUFEI_ATM_RX_HECD_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_HECD_S, WUFEI_ATM_RX_HECD_W)
#define WUFEI_ATM_RX_HECD_M \
        WUFEI_MASK(WUFEI_ATM_RX_HECD_S, WUFEI_ATM_RX_HECD_W)

#define WUFEI_ATM_RX_HEN_S (5)
#define WUFEI_ATM_RX_HEN_W (1)
#define WUFEI_ATM_RX_HEN_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_HEN_S)
#define WUFEI_ATM_RX_HEN_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_HEN_S, WUFEI_ATM_RX_HEN_W)
#define WUFEI_ATM_RX_HEN_M \
        WUFEI_MASK(WUFEI_ATM_RX_HEN_S, WUFEI_ATM_RX_HEN_W)

#define WUFEI_ATM_RX_CDM_S (4)
#define WUFEI_ATM_RX_CDM_W (1)
#define WUFEI_ATM_RX_CDM_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_CDM_S)
#define WUFEI_ATM_RX_CDM_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_CDM_S, WUFEI_ATM_RX_CDM_W)
#define WUFEI_ATM_RX_CDM_M \
        WUFEI_MASK(WUFEI_ATM_RX_CDM_S, WUFEI_ATM_RX_CDM_W)

#define WUFEI_ATM_RX_SYNC_STATE_S (14)
#define WUFEI_ATM_RX_SYNC_STATE_W (2)
#define WUFEI_ATM_RX_SYNC_STATE_F(v) WUFEI_FIELD(v, WUFEI_ATM_RX_SYNC_STATE_S)
#define WUFEI_ATM_RX_SYNC_STATE_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_RX_SYNC_STATE_S, WUFEI_ATM_RX_SYNC_STATE_W)
#define WUFEI_ATM_RX_SYNC_STATE_M \
        WUFEI_MASK(WUFEI_ATM_RX_SYNC_STATE_S, WUFEI_ATM_RX_SYNC_STATE_W)


#define WUFEI_ATM_TX_MODE_TYPE_S (12)
#define WUFEI_ATM_TX_MODE_TYPE_W (4)
#define WUFEI_ATM_TX_MODE_TYPE_F(v) WUFEI_FIELD(v, WUFEI_ATM_TX_MODE_TYPE_S)
#define WUFEI_ATM_TX_MODE_TYPE_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_TX_MODE_TYPE_S, WUFEI_ATM_TX_MODE_TYPE_W)
#define WUFEI_ATM_TX_MODE_TYPE_M \
        WUFEI_MASK(WUFEI_ATM_TX_MODE_TYPE_S, WUFEI_ATM_TX_MODE_TYPE_W)

#define WUFEI_ATM_TX_MODE_EN_S (11)
#define WUFEI_ATM_TX_MODE_EN_W (1)
#define WUFEI_ATM_TX_MODE_EN_F(v) WUFEI_FIELD(v, WUFEI_ATM_TX_MODE_EN_S)
#define WUFEI_ATM_TX_MODE_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_TX_MODE_EN_S, WUFEI_ATM_TX_MODE_EN_W)
#define WUFEI_ATM_TX_MODE_EN_M \
        WUFEI_MASK(WUFEI_ATM_TX_MODE_EN_S, WUFEI_ATM_TX_MODE_EN_W)

#define WUFEI_ATM_TX_SCRAMBLER_S (10)
#define WUFEI_ATM_TX_SCRAMBLER_W (1)
#define WUFEI_ATM_TX_SCRAMBLER_F(v) WUFEI_FIELD(v, WUFEI_ATM_TX_SCRAMBLER_S)
#define WUFEI_ATM_TX_SCRAMBLER_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_TX_SCRAMBLER_S, WUFEI_ATM_TX_SCRAMBLER_W)
#define WUFEI_ATM_TX_SCRAMBLER_M \
        WUFEI_MASK(WUFEI_ATM_TX_SCRAMBLER_S, WUFEI_ATM_TX_SCRAMBLER_W)

#define WUFEI_ATM_TX_COSET_S (9)
#define WUFEI_ATM_TX_COSET_W (1)
#define WUFEI_ATM_TX_COSET_F(v) WUFEI_FIELD(v, WUFEI_ATM_TX_COSET_S)
#define WUFEI_ATM_TX_COSET_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_TX_COSET_S, WUFEI_ATM_TX_COSET_W)
#define WUFEI_ATM_TX_COSET_M \
        WUFEI_MASK(WUFEI_ATM_TX_COSET_S, WUFEI_ATM_TX_COSET_W)

#define WUFEI_ATM_TX_CLP_S (8)
#define WUFEI_ATM_TX_CLP_W (1)
#define WUFEI_ATM_TX_CLP_F(v) WUFEI_FIELD(v, WUFEI_ATM_TX_CLP_S)
#define WUFEI_ATM_TX_CLP_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_TX_CLP_S, WUFEI_ATM_TX_CLP_W)
#define WUFEI_ATM_TX_CLP_M \
        WUFEI_MASK(WUFEI_ATM_TX_CLP_S, WUFEI_ATM_TX_CLP_W)

#define WUFEI_ATM_TX_UNDERRUN_S (15)
#define WUFEI_ATM_TX_UNDERRUN_W (1)
#define WUFEI_ATM_TX_UNDERRUN_F(v) WUFEI_FIELD(v, WUFEI_ATM_TX_UNDERRUN_S)
#define WUFEI_ATM_TX_UNDERRUN_V(f) \
        WUFEI_VALUE(f, WUFEI_ATM_TX_UNDERRUN_S, WUFEI_ATM_TX_UNDERRUN_W)
#define WUFEI_ATM_TX_UNDERRUN_M \
        WUFEI_MASK(WUFEI_ATM_TX_UNDERRUN_S, WUFEI_ATM_TX_UNDERRUN_W)


/* POS machine */
#define WUFEI_POS_RX_MODE_TYPE_S (12)
#define WUFEI_POS_RX_MODE_TYPE_W (4)
#define WUFEI_POS_RX_MODE_TYPE_F(v) WUFEI_FIELD(v, WUFEI_POS_RX_MODE_TYPE_S)
#define WUFEI_POS_RX_MODE_TYPE_V(f) \
        WUFEI_VALUE(f, WUFEI_POS_RX_MODE_TYPE_S, WUFEI_POS_RX_MODE_TYPE_W)
#define WUFEI_POS_RX_MODE_TYPE_M \
        WUFEI_MASK(WUFEI_POS_RX_MODE_TYPE_S, WUFEI_POS_RX_MODE_TYPE_W)

#define WUFEI_POS_RX_MODE_EN_S (11)
#define WUFEI_POS_RX_MODE_EN_W (1)
#define WUFEI_POS_RX_MODE_EN_F(v) WUFEI_FIELD(v, WUFEI_POS_RX_MODE_EN_S)
#define WUFEI_POS_RX_MODE_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_POS_RX_MODE_EN_S, WUFEI_POS_RX_MODE_EN_W)
#define WUFEI_POS_RX_MODE_EN_M \
        WUFEI_MASK(WUFEI_POS_RX_MODE_EN_S, WUFEI_POS_RX_MODE_EN_W)

#define WUFEI_POS_RX_FCS_S (10)
#define WUFEI_POS_RX_FCS_W (1)
#define WUFEI_POS_RX_FCS_F(v) WUFEI_FIELD(v, WUFEI_POS_RX_FCS_S)
#define WUFEI_POS_RX_FCS_V(f) \
        WUFEI_VALUE(f, WUFEI_POS_RX_FCS_S, WUFEI_POS_RX_FCS_W)
#define WUFEI_POS_RX_FCS_M \
        WUFEI_MASK(WUFEI_POS_RX_FCS_S, WUFEI_POS_RX_FCS_W)

#define WUFEI_POS_RX_DEN_S (9)
#define WUFEI_POS_RX_DEN_W (1)
#define WUFEI_POS_RX_DEN_F(v) WUFEI_FIELD(v, WUFEI_POS_RX_DEN_S)
#define WUFEI_POS_RX_DEN_V(f) \
        WUFEI_VALUE(f, WUFEI_POS_RX_DEN_S, WUFEI_POS_RX_DEN_W)
#define WUFEI_POS_RX_DEN_M \
        WUFEI_MASK(WUFEI_POS_RX_DEN_S, WUFEI_POS_RX_DEN_W)

#define WUFEI_POS_TX_MODE_TYPE_S (12)
#define WUFEI_POS_TX_MODE_TYPE_W (4)
#define WUFEI_POS_TX_MODE_TYPE_F(v) WUFEI_FIELD(v, WUFEI_POS_TX_MODE_TYPE_S)
#define WUFEI_POS_TX_MODE_TYPE_V(f) \
        WUFEI_VALUE(f, WUFEI_POS_TX_MODE_TYPE_S, WUFEI_POS_TX_MODE_TYPE_W)
#define WUFEI_POS_TX_MODE_TYPE_M \
        WUFEI_MASK(WUFEI_POS_TX_MODE_TYPE_S, WUFEI_POS_TX_MODE_TYPE_W)

#define WUFEI_POS_TX_MODE_EN_S (11)
#define WUFEI_POS_TX_MODE_EN_W (1)
#define WUFEI_POS_TX_MODE_EN_F(v) WUFEI_FIELD(v, WUFEI_POS_TX_MODE_EN_S)
#define WUFEI_POS_TX_MODE_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_POS_TX_MODE_EN_S, WUFEI_POS_TX_MODE_EN_W)
#define WUFEI_POS_TX_MODE_EN_M \
        WUFEI_MASK(WUFEI_POS_TX_MODE_EN_S, WUFEI_POS_TX_MODE_EN_W)

#define WUFEI_POS_TX_FCS_S (10)
#define WUFEI_POS_TX_FCS_W (1)
#define WUFEI_POS_TX_FCS_F(v) WUFEI_FIELD(v, WUFEI_POS_TX_FCS_S)
#define WUFEI_POS_TX_FCS_V(f) \
        WUFEI_VALUE(f, WUFEI_POS_TX_FCS_S, WUFEI_POS_TX_FCS_W)
#define WUFEI_POS_TX_FCS_M \
        WUFEI_MASK(WUFEI_POS_TX_FCS_S, WUFEI_POS_TX_FCS_W)

#define WUFEI_POS_TX_SEN_S (9)
#define WUFEI_POS_TX_SEN_W (1)
#define WUFEI_POS_TX_SEN_F(v) WUFEI_FIELD(v, WUFEI_POS_TX_SEN_S)
#define WUFEI_POS_TX_SEN_V(f) \
        WUFEI_VALUE(f, WUFEI_POS_TX_SEN_S, WUFEI_POS_TX_SEN_W)
#define WUFEI_POS_TX_SEN_M \
        WUFEI_MASK(WUFEI_POS_TX_SEN_S, WUFEI_POS_TX_SEN_W)

#define WUFEI_POS_TX_NOF_INTER_FLAGS_S (4)
#define WUFEI_POS_TX_NOF_INTER_FLAGS_W (4)
#define WUFEI_POS_TX_NOF_INTER_FLAGS_F(v) WUFEI_FIELD(v, WUFEI_POS_TX_NOF_INTER_FLAGS_S)
#define WUFEI_POS_TX_NOF_INTER_FLAGS_V(f) \
        WUFEI_VALUE(f, WUFEI_POS_TX_NOF_INTER_FLAGS_S, WUFEI_POS_TX_NOF_INTER_FLAGS_W)
#define WUFEI_POS_TX_NOF_INTER_FLAGS_M \
        WUFEI_MASK(WUFEI_POS_TX_NOF_INTER_FLAGS_S, WUFEI_POS_TX_NOF_INTER_FLAGS_W)


#endif /* WUFEI_HW_MACHINE_H*/
