/*****************************************************************************
 * (C) Copyright 2000-2006, Wintegra. All rights reserved.
 * WINTEGRA CONFIDENTIAL PROPRIETARY
 * Contains Confidential Proprietary information of Wintegra.
 * Reverse engineering is prohibited.
 * The copyright notice does not imply publication.
 ****************************************************************************/

/*****************************************************************************
 *
 * File: wufei_hw_globals.h
 *
 * Purpose: the general registers definition for the UFE4 FPGA
 *
 ****************************************************************************/

#ifndef WUFEI_HW_GLOBALS_H
#define WUFEI_HW_GLOBALS_H

#ifndef WUFE_TYPES_H
#include "wufe_types.h"
#endif

#ifndef WUFEI_HW_TYPES_H
#include "wufei_hw_types.h"
#endif

typedef struct
{
   WUFEI_reg_space release_id;
   WUFEI_reg_space secondary_release_id;
   WUFEI_reg_space reserved1[2];
   WUFEI_reg_space build_number;
   WUFEI_reg_space reserved2[3];
   WUFEI_reg_space global_int;
   WUFEI_reg_space global_mask_int;
   WUFEI_reg_space reserved3[6];
   WUFEI_reg_space sys_config;
   WUFEI_reg_space reserved4[7];
   WUFEI_reg_space core_config;
   WUFEI_reg_space reserved5[11];
}WUFEI_hw_gen_regs;

/************************************/
/* Release ID register structure    */
/************************************/
#define WUFEI_UFE_RELEASE_ID_S (0)
#define WUFEI_UFE_RELEASE_ID_W (16)
#define WUFEI_UFE_RELEASE_ID_F(v) WUFEI_FIELD(v, WUFEI_UFE_RELEASE_ID_S)
#define WUFEI_UFE_RELEASE_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_RELEASE_ID_S, WUFEI_UFE_RELEASE_ID_W)
#define WUFEI_UFE_RELEASE_ID_M \
        WUFEI_MASK(WUFEI_UFE_RELEASE_ID_S, WUFEI_UFE_RELEASE_ID_W)

/********************************************/
/* Secondary Release ID register structure  */
/********************************************/
#define WUFEI_UFE_SECONDARY_RELEASE_ID_S (0)
#define WUFEI_UFE_SECONDARY_RELEASE_ID_W (16)
#define WUFEI_UFE_SECONDARY_RELEASE_ID_F(v) WUFEI_FIELD(v, WUFEI_UFE_SECONDARY_RELEASE_ID_S)
#define WUFEI_UFE_SECONDARY_RELEASE_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_SECONDARY_RELEASE_ID_S, WUFEI_UFE_SECONDARY_RELEASE_ID_W)
#define WUFEI_UFE_SECONDARY_RELEASE_ID_M \
        WUFEI_MASK(WUFEI_UFE_SECONDARY_RELEASE_ID_S, WUFEI_UFE_SECONDARY_RELEASE_ID_W)

/***************************************/
/* Build number register structure     */
/***************************************/
#define WUFEI_UFE_BUILD_NUM_S (0)
#define WUFEI_UFE_BUILD_NUM_W (16)
#define WUFEI_UFE_BUILD_NUM_F(v) WUFEI_FIELD(v, WUFEI_UFE_BUILD_NUM_S)
#define WUFEI_UFE_BUILD_NUM_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_BUILD_NUM_S, WUFEI_UFE_BUILD_NUM_W)
#define WUFEI_UFE_BUILD_NUM_M \
        WUFEI_MASK(WUFEI_UFE_BUILD_NUM_S, WUFEI_UFE_BUILD_NUM_W)

/********************************************/
/* General Configuration register structure */
/********************************************/
#define WUFEI_UFE_FRAMER_MODE_S (0)
#define WUFEI_UFE_FRAMER_MODE_W (2)
#define WUFEI_UFE_FRAMER_MODE_F(v) WUFEI_FIELD(v, WUFEI_UFE_FRAMER_MODE_S)
#define WUFEI_UFE_FRAMER_MODE_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_FRAMER_MODE_S, WUFEI_UFE_FRAMER_MODE_W)
#define WUFEI_UFE_FRAMER_MODE_M \
        WUFEI_MASK(WUFEI_UFE_FRAMER_MODE_S, WUFEI_UFE_FRAMER_MODE_W)

#define WUFEI_UFE_EMPHY_SETUP_MODE_S (2)
#define WUFEI_UFE_EMPHY_SETUP_MODE_W (2)
#define WUFEI_UFE_EMPHY_SETUP_MODE_F(v) WUFEI_FIELD(v, WUFEI_UFE_EMPHY_SETUP_MODE_S)
#define WUFEI_UFE_EMPHY_SETUP_MODE_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_EMPHY_SETUP_MODE_S, WUFEI_UFE_EMPHY_SETUP_MODE_W)
#define WUFEI_UFE_EMPHY_SETUP_MODE_M \
        WUFEI_MASK(WUFEI_UFE_EMPHY_SETUP_MODE_S, WUFEI_UFE_EMPHY_SETUP_MODE_W)

#define WUFEI_UFE_FM_NUM_OF_BANKS_S (6)
#define WUFEI_UFE_FM_NUM_OF_BANKS_W (1)
#define WUFEI_UFE_FM_NUM_OF_BANKS_F(v) WUFEI_FIELD(v, WUFEI_UFE_FM_NUM_OF_BANKS_S)
#define WUFEI_UFE_FM_NUM_OF_BANKS_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_FM_NUM_OF_BANKS_S, WUFEI_UFE_FM_NUM_OF_BANKS_W)
#define WUFEI_UFE_FM_NUM_OF_BANKS_M \
        WUFEI_MASK(WUFEI_UFE_FM_NUM_OF_BANKS_S, WUFEI_UFE_FM_NUM_OF_BANKS_W)

#define WUFEI_UFE_BANDWIDTH_S (12)
#define WUFEI_UFE_BANDWIDTH_W (2)
#define WUFEI_UFE_BANDWIDTH_F(v) WUFEI_FIELD(v, WUFEI_UFE_BANDWIDTH_S)
#define WUFEI_UFE_BANDWIDTH_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_BANDWIDTH_S, WUFEI_UFE_BANDWIDTH_W)
#define WUFEI_UFE_BANDWIDTH_M \
        WUFEI_MASK(WUFEI_UFE_BANDWIDTH_S, WUFEI_UFE_BANDWIDTH_W)

#define WUFEI_GLOBAL_CFG_BANDWIDTH_OC3 0
#define WUFEI_GLOBAL_CFG_BANDWIDTH_OC6 4 /* This configuration is not coded in the HW*/
#define WUFEI_GLOBAL_CFG_BANDWIDTH_OC12 1
#define WUFEI_GLOBAL_CFG_BANDWIDTH_OC24 2
#define WUFEI_GLOBAL_CFG_BANDWIDTH_OC48 3


#define WUFEI_DDR_INIT_TIMEOUT 300
#define WUFEI_FM_NUM_OF_BANKS_LOW 4
#define WUFEI_FM_NUM_OF_BANKS_HIGH 8


#if WUFEI_UFE448 
#define WUFEI_MAX_N_PHY_PER_CORE 1360 /*in UFE448 there are only 1024 phy per core, but the relevant RAMs are reserved in the extra space.*/
#define WUFEI_EMPHY_PORT_ID_OFFSET 2048 //1024 /*relevant only for UFE448; DPS currently supports only 2048 , must comply*/
#else /* for S6 the values should be as below */
#define WUFEI_MAX_N_PHY_PER_CORE 1352 /*in UFE448 there are only 1024 phy per core, but the relevant RAMs are reserved in the extra space.*/
#define WUFEI_EMPHY_PORT_ID_OFFSET 2048 /*relevant only for UFE448; DPS currently supports only 2048 , must comply with UFE4_MAX_PHY_PER_CORE & WPI_CESOP_EMPHY_CORE_ID_OFFSET*/
#endif

/* System frequencies */
#define WUFEI_SYSTEM_CLOCK_155_52 155520000
#define WUFEI_SYSTEM_CLOCK_77_76   77760000
#define WUFEI_SYSTEM_CLOCK_38_88   38880000
#define WUFEI_SYSTEM_CLOCK_19_44   19440000

/*********************************************/
/* UFE core configuration register structure */
/*********************************************/

#define WUFEI_UFE_CORE_DDR_1_INIT_DONE_S (15)
#define WUFEI_UFE_CORE_DDR_1_INIT_DONE_W (1)
#define WUFEI_UFE_CORE_DDR_1_INIT_DONE_F(v) WUFEI_FIELD(v, WUFEI_UFE_CORE_DDR_1_INIT_DONE_S)
#define WUFEI_UFE_CORE_DDR_1_INIT_DONE_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_CORE_DDR_1_INIT_DONE_S, WUFEI_UFE_CORE_DDR_1_INIT_DONE_W)
#define WUFEI_UFE_CORE_DDR_1_INIT_DONE_M \
        WUFEI_MASK(WUFEI_UFE_CORE_DDR_1_INIT_DONE_S, WUFEI_UFE_CORE_DDR_1_INIT_DONE_W)

#define WUFEI_UFE_CORE_DDR_0_INIT_DONE_S (14)
#define WUFEI_UFE_CORE_DDR_0_INIT_DONE_W (1)
#define WUFEI_UFE_CORE_DDR_0_INIT_DONE_F(v) WUFEI_FIELD(v, WUFEI_UFE_CORE_DDR_0_INIT_DONE_S)
#define WUFEI_UFE_CORE_DDR_0_INIT_DONE_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_CORE_DDR_0_INIT_DONE_S, WUFEI_UFE_CORE_DDR_0_INIT_DONE_W)
#define WUFEI_UFE_CORE_DDR_0_INIT_DONE_M \
        WUFEI_MASK(WUFEI_UFE_CORE_DDR_0_INIT_DONE_S, WUFEI_UFE_CORE_DDR_0_INIT_DONE_W)

#define WUFEI_UFE_CORE_1_INCLUDED_S (12)
#define WUFEI_UFE_CORE_1_INCLUDED_W (1)
#define WUFEI_UFE_CORE_1_INCLUDED_F(v) WUFEI_FIELD(v, WUFEI_UFE_CORE_1_INCLUDED_S)
#define WUFEI_UFE_CORE_1_INCLUDED_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_CORE_1_INCLUDED_S, WUFEI_UFE_CORE_1_INCLUDED_W)
#define WUFEI_UFE_CORE_1_INCLUDED_M \
        WUFEI_MASK(WUFEI_UFE_CORE_1_INCLUDED_S, WUFEI_UFE_CORE_1_INCLUDED_W)

#define WUFEI_UFE_MAX_BUF_SIZE_S (8)
#define WUFEI_UFE_MAX_BUF_SIZE_W (2)
#define WUFEI_UFE_MAX_BUF_SIZE_F(v) WUFEI_FIELD(v, WUFEI_UFE_MAX_BUF_SIZE_S)
#define WUFEI_UFE_MAX_BUF_SIZE_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_MAX_BUF_SIZE_S, WUFEI_UFE_MAX_BUF_SIZE_W)
#define WUFEI_UFE_MAX_BUF_SIZE_M \
        WUFEI_MASK(WUFEI_UFE_MAX_BUF_SIZE_S, WUFEI_UFE_MAX_BUF_SIZE_W)

#define WUFEI_GEN_CFG_SYS_REG_MACHINE_S (0)
#define WUFEI_GEN_CFG_SYS_REG_MACHINE_W (4)
#define WUFEI_GEN_CFG_SYS_REG_MACHINE_V(f) \
   WUFEI_VALUE(f, WUFEI_GEN_CFG_SYS_REG_MACHINE_S, WUFEI_GEN_CFG_SYS_REG_MACHINE_W)

#define WUFEI_GEN_CFG_SYS_REG_MACHINE_TRANS 0x1
#define WUFEI_GEN_CFG_SYS_REG_MACHINE_TRANS_MF 0x2
#define WUFEI_GEN_CFG_SYS_REG_MACHINE_ATM   0x4
#define WUFEI_GEN_CFG_SYS_REG_MACHINE_HDLC  0x8

/***************************************/
/* Global interrupt register structure */
/***************************************/
#define WUFEI_UFE_GLOBAL_INT_TDM0_S (0)
#define WUFEI_UFE_GLOBAL_INT_TDM0_W (1)
#define WUFEI_UFE_GLOBAL_INT_TDM0_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_TDM0_S)
#define WUFEI_UFE_GLOBAL_INT_TDM0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_TDM0_S, WUFEI_UFE_GLOBAL_INT_TDM0_W)
#define WUFEI_UFE_GLOBAL_INT_TDM0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_TDM0_S, WUFEI_UFE_GLOBAL_INT_TDM0_W)

#define WUFEI_UFE_GLOBAL_INT_TDM1_S (4)
#define WUFEI_UFE_GLOBAL_INT_TDM1_W (1)
#define WUFEI_UFE_GLOBAL_INT_TDM1_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_TDM1_S)
#define WUFEI_UFE_GLOBAL_INT_TDM1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_TDM1_S, WUFEI_UFE_GLOBAL_INT_TDM1_W)
#define WUFEI_UFE_GLOBAL_INT_TDM1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_TDM1_S, WUFEI_UFE_GLOBAL_INT_TDM1_W)

#define WUFEI_UFE_GLOBAL_INT_MACHINE0_S (1)
#define WUFEI_UFE_GLOBAL_INT_MACHINE0_W (1)
#define WUFEI_UFE_GLOBAL_INT_MACHINE0_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_MACHINE0_S)
#define WUFEI_UFE_GLOBAL_INT_MACHINE0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_MACHINE0_S, WUFEI_UFE_GLOBAL_INT_MACHINE0_W)
#define WUFEI_UFE_GLOBAL_INT_MACHINE0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_MACHINE0_S, WUFEI_UFE_GLOBAL_INT_MACHINE0_W)

#define WUFEI_UFE_GLOBAL_INT_MACHINE1_S (5)
#define WUFEI_UFE_GLOBAL_INT_MACHINE1_W (1)
#define WUFEI_UFE_GLOBAL_INT_MACHINE1_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_MACHINE1_S)
#define WUFEI_UFE_GLOBAL_INT_MACHINE1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_MACHINE1_S, WUFEI_UFE_GLOBAL_INT_MACHINE1_W)
#define WUFEI_UFE_GLOBAL_INT_MACHINE1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_MACHINE1_S, WUFEI_UFE_GLOBAL_INT_MACHINE1_W)

#define WUFEI_UFE_GLOBAL_INT_FM0_S (2)
#define WUFEI_UFE_GLOBAL_INT_FM0_W (1)
#define WUFEI_UFE_GLOBAL_INT_FM0_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_FM0_S)
#define WUFEI_UFE_GLOBAL_INT_FM0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_FM0_S, WUFEI_UFE_GLOBAL_INT_FM0_W)
#define WUFEI_UFE_GLOBAL_INT_FM0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_FM0_S, WUFEI_UFE_GLOBAL_INT_FM0_W)

#define WUFEI_UFE_GLOBAL_INT_FM1_S (6)
#define WUFEI_UFE_GLOBAL_INT_FM1_W (1)
#define WUFEI_UFE_GLOBAL_INT_FM1_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_FM1_S)
#define WUFEI_UFE_GLOBAL_INT_FM1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_FM1_S, WUFEI_UFE_GLOBAL_INT_FM1_W)
#define WUFEI_UFE_GLOBAL_INT_FM1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_FM1_S, WUFEI_UFE_GLOBAL_INT_FM1_W)

#define WUFEI_UFE_GLOBAL_INT_EMPHY0_S (8)
#define WUFEI_UFE_GLOBAL_INT_EMPHY0_W (1)
#define WUFEI_UFE_GLOBAL_INT_EMPHY0_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_EMPHY0_S)
#define WUFEI_UFE_GLOBAL_INT_EMPHY0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_EMPHY0_S, WUFEI_UFE_GLOBAL_INT_EMPHY0_W)
#define WUFEI_UFE_GLOBAL_INT_EMPHY0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_EMPHY0_S, WUFEI_UFE_GLOBAL_INT_EMPHY0_W)

#define WUFEI_UFE_GLOBAL_INT_EMPHY1_S (9)
#define WUFEI_UFE_GLOBAL_INT_EMPHY1_W (1)
#define WUFEI_UFE_GLOBAL_INT_EMPHY1_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_EMPHY1_S)
#define WUFEI_UFE_GLOBAL_INT_EMPHY1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_EMPHY1_S, WUFEI_UFE_GLOBAL_INT_EMPHY1_W)
#define WUFEI_UFE_GLOBAL_INT_EMPHY1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_EMPHY1_S, WUFEI_UFE_GLOBAL_INT_EMPHY1_W)

#define WUFEI_UFE_GLOBAL_INT_CR_S (12)
#define WUFEI_UFE_GLOBAL_INT_CR_W (1)
#define WUFEI_UFE_GLOBAL_INT_CR_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_INT_CR_S)
#define WUFEI_UFE_GLOBAL_INT_CR_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_INT_CR_S, WUFEI_UFE_GLOBAL_INT_CR_W)
#define WUFEI_UFE_GLOBAL_INT_CR_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_INT_CR_S, WUFEI_UFE_GLOBAL_INT_CR_W)

/********************************************/
/* Global mask interrupt register structure */
/********************************************/
#define WUFEI_UFE_GLOBAL_MASK_INT_TDM0_S (0)
#define WUFEI_UFE_GLOBAL_MASK_INT_TDM0_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_TDM0_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_TDM0_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_TDM0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_TDM0_S, WUFEI_UFE_GLOBAL_MASK_INT_TDM0_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_TDM0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_TDM0_S, WUFEI_UFE_GLOBAL_MASK_INT_TDM0_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_TDM1_S (4)
#define WUFEI_UFE_GLOBAL_MASK_INT_TDM1_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_TDM1_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_TDM1_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_TDM1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_TDM1_S, WUFEI_UFE_GLOBAL_MASK_INT_TDM1_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_TDM1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_TDM1_S, WUFEI_UFE_GLOBAL_MASK_INT_TDM1_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_MACHINE0_S (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_MACHINE0_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_MACHINE0_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_MACHINE0_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_MACHINE0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_MACHINE0_S, WUFEI_UFE_GLOBAL_MASK_INT_MACHINE0_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_MACHINE0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_MACHINE0_S, WUFEI_UFE_GLOBAL_MASK_INT_MACHINE0_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_MACHINE1_S (5)
#define WUFEI_UFE_GLOBAL_MASK_INT_MACHINE1_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_MACHINE1_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_MACHINE1_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_MACHINE1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_MACHINE1_S, WUFEI_UFE_GLOBAL_MASK_INT_MACHINE1_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_MACHINE1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_MACHINE1_S, WUFEI_UFE_GLOBAL_MASK_INT_MACHINE1_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_FM0_S (2)
#define WUFEI_UFE_GLOBAL_MASK_INT_FM0_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_FM0_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_FM0_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_FM0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_FM0_S, WUFEI_UFE_GLOBAL_MASK_INT_FM0_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_FM0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_FM0_S, WUFEI_UFE_GLOBAL_MASK_INT_FM0_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_FM1_S (6)
#define WUFEI_UFE_GLOBAL_MASK_INT_FM1_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_FM1_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_FM1_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_FM1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_FM1_S, WUFEI_UFE_GLOBAL_MASK_INT_FM1_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_FM1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_FM1_S, WUFEI_UFE_GLOBAL_MASK_INT_FM1_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY0_S (8)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY0_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY0_F(v) \
        WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_EMPHY0_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY0_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_EMPHY0_S,\
        WUFEI_UFE_GLOBAL_MASK_INT_EMPHY0_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY0_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_EMPHY0_S,\
        WUFEI_UFE_GLOBAL_MASK_INT_EMPHY0_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY1_S (9)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY1_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY1_F(v) \
        WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_EMPHY1_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY1_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_EMPHY1_S,\
        WUFEI_UFE_GLOBAL_MASK_INT_EMPHY1_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_EMPHY1_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_EMPHY1_S,\
        WUFEI_UFE_GLOBAL_MASK_INT_EMPHY1_W)

#define WUFEI_UFE_GLOBAL_MASK_INT_CR_S (12)
#define WUFEI_UFE_GLOBAL_MASK_INT_CR_W (1)
#define WUFEI_UFE_GLOBAL_MASK_INT_CR_F(v) WUFEI_FIELD(v, WUFEI_UFE_GLOBAL_MASK_INT_CR_S)
#define WUFEI_UFE_GLOBAL_MASK_INT_CR_V(f) \
        WUFEI_VALUE(f, WUFEI_UFE_GLOBAL_MASK_INT_CR_S, WUFEI_UFE_GLOBAL_MASK_INT_CR_W)
#define WUFEI_UFE_GLOBAL_MASK_INT_CR_M \
        WUFEI_MASK(WUFEI_UFE_GLOBAL_MASK_INT_CR_S, WUFEI_UFE_GLOBAL_MASK_INT_CR_W)

#endif /*WUFEI_HW_GLOBALS_H*/
