#ifndef __MORRIS_COFIG_H__
#define __MORRIS_COFIG_H__

#define MORRIS_CR_ON	(1)

#define USE_MORRIS_CONFIG	(0)
#define USE_MORRIS_REF_CLOCK	WPX_UFE_FRAMER_TRANSMIT_TIMING_INPUT_REFERENCE_CLOCK


#define MORRIS_ENABLE_PM_PRINT_COUNTER	(0)	// 0 = enable if(count)
#define MORRIS_PM_PORT_PRINT_WITHOUT_COUNTER	(0)
#define MORRIS_PM_COUNT_CLEAN	(1)
#define MORRIS_PRINT_HO_COUNTER	(0)	// this should always be 0, never 1
#define MORRIS_PRINT_LO_COUNTER	(0)

#define MORRIS_ENABLE_STM_1	(0)
#define MORRIS_SKIP_ALARMS	(1)


#define MORRIS_USE_VC4	(1)
#define MORRIS_DISABLE_MON_STATE	(0)


#define MORRIS_FACTOR	(1)

#define MORRIS_ENABLE_FREERUN_MODE	(0)
#define MORRIS_ENABLE_PDH_ALRAM_PRINT	(0)

#define MORRIS_ENABLE_LOS_AIS	(1)
#define MORRIS_ENABLE_PATH_ALARM	(1)

#endif


