/*****************************************************************************
 * (C) Copyright 2000-2006, Wintegra. All rights reserved.
 * WINTEGRA CONFIDENTIAL PROPRIETARY
 * Contains Confidential Proprietary information of Wintegra.
 * Reverse engineering is prohibited.
 * The copyright notice does not imply publication.
 ****************************************************************************/

/*****************************************************************************
 *
 * File: wufei_hw_tdm.h
 *
 * Purpose: the UFE TDM  macro and structures
 *
 ****************************************************************************/
#ifndef WUFEI_HW_TDM_H
#define WUFEI_HW_TDM_H

#ifndef WUFE_SYSTEM_H
#include "wufe_system.h"
#endif

#ifndef WUFEI_HW_TYPES_H
#include "wufei_hw_types.h"
#endif

typedef struct
{
      WUFEI_reg_space tdm_ind_low; /*TDM indirect address low*/
      WUFEI_reg_space tdm_ind_high; /*TDM indirect address high*/
      WUFEI_reg_space tdm_ind_cmd; /*TDM indirect address cmd*/
      WUFEI_reg_space tdm_ind_data; /*TDM indirect address data*/
      WUFEI_reg_space reserved1[4]; /*reserved for future enhancements*/
      WUFEI_reg_space tdm_interrupt; /*TDM interrupt*/
      WUFEI_reg_space tdm_interrupt_mask; /*TDM interrupt mask*/
      WUFEI_reg_space reserved2[6]; /*reserved for future enhancements*/
      WUFEI_reg_space tdm_mode; /*TDM mode register*/
      WUFEI_reg_space tdm_idle; /*TDM idle data and cas*/
      WUFEI_reg_space tdm_sys_lb; /*TDM system loopback*/
      WUFEI_reg_space tdm_pdh_line_lb; /*TDM pdh line loopback*/
      WUFEI_reg_space tdm_pdh_system_lb; /*TDM pdh system loopback*/
}WUFEI_hw_tdm;

#define MAX_NUM_OF_SLOTS 32
#define WUFEI_TDM_MODE_MULTI_FRAMED 2
#define WUFEI_TDM_TUG2_DCC 0x7
#define WUFEI_TDM_MODE_RAM_TRIBUTARY_TYPE_CLEAR_CHANNEL 0x3

/* CHANNEL ID */

#define WUFEI_TDM_CH_ID_DS0_S (0)
#define WUFEI_TDM_CH_ID_DS0_W (5)
#define WUFEI_TDM_CH_ID_DS0_F(v) WUFEI_FIELD(v, WUFEI_TDM_CH_ID_DS0_S)
#define WUFEI_TDM_CH_ID_DS0_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_CH_ID_DS0_S, WUFEI_TDM_CH_ID_DS0_W)
#define WUFEI_TDM_CH_ID_DS0_M \
        WUFEI_MASK(WUFEI_TDM_CH_ID_DS0_S, WUFEI_TDM_CH_ID_DS0_W)

#define WUFEI_TDM_CH_ID_TU_S (5)
#define WUFEI_TDM_CH_ID_TU_W (2)
#define WUFEI_TDM_CH_ID_TU_F(v) WUFEI_FIELD(v, WUFEI_TDM_CH_ID_TU_S)
#define WUFEI_TDM_CH_ID_TU_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_CH_ID_TU_S, WUFEI_TDM_CH_ID_TU_W)
#define WUFEI_TDM_CH_ID_TU_M \
        WUFEI_MASK(WUFEI_TDM_CH_ID_TU_S, WUFEI_TDM_CH_ID_TU_W)

#define WUFEI_TDM_CH_ID_TUG2_S (7)
#define WUFEI_TDM_CH_ID_TUG2_W (3)
#define WUFEI_TDM_CH_ID_TUG2_F(v) WUFEI_FIELD(v, WUFEI_TDM_CH_ID_TUG2_S)
#define WUFEI_TDM_CH_ID_TUG2_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_CH_ID_TUG2_S, WUFEI_TDM_CH_ID_TUG2_W)
#define WUFEI_TDM_CH_ID_TUG2_M \
        WUFEI_MASK(WUFEI_TDM_CH_ID_TUG2_S, WUFEI_TDM_CH_ID_TUG2_W)

#define WUFEI_TDM_CH_ID_AUG1_S (10)
#define WUFEI_TDM_CH_ID_AUG1_W (2)
#define WUFEI_TDM_CH_ID_AUG1_F(v) WUFEI_FIELD(v, WUFEI_TDM_CH_ID_AUG1_S)
#define WUFEI_TDM_CH_ID_AUG1_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_CH_ID_AUG1_S, WUFEI_TDM_CH_ID_AUG1_W)
#define WUFEI_TDM_CH_ID_AUG1_M \
        WUFEI_MASK(WUFEI_TDM_CH_ID_AUG1_S, WUFEI_TDM_CH_ID_AUG1_W)

#define WUFEI_TDM_CH_ID_AUG4_S (12)
#define WUFEI_TDM_CH_ID_AUG4_W (1)
#define WUFEI_TDM_CH_ID_AUG4_F(v) WUFEI_FIELD(v, WUFEI_TDM_CH_ID_AUG4_S)
#define WUFEI_TDM_CH_ID_AUG4_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_CH_ID_AUG4_S, WUFEI_TDM_CH_ID_AUG4_W)
#define WUFEI_TDM_CH_ID_AUG4_M \
        WUFEI_MASK(WUFEI_TDM_CH_ID_AUG4_S, WUFEI_TDM_CH_ID_AUG4_W)

#define WUFEI_TDM_CH_ID_AU3_S (13)
#define WUFEI_TDM_CH_ID_AU3_W (2)
#define WUFEI_TDM_CH_ID_AU3_F(v) WUFEI_FIELD(v, WUFEI_TDM_CH_ID_AU3_S)
#define WUFEI_TDM_CH_ID_AU3_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_CH_ID_AU3_S, WUFEI_TDM_CH_ID_AU3_W)
#define WUFEI_TDM_CH_ID_AU3_M \
        WUFEI_MASK(WUFEI_TDM_CH_ID_AU3_S, WUFEI_TDM_CH_ID_AU3_W)

/**************/


#define WUFEI_TDM_SYSTEM_LB_EN_S (0)
#define WUFEI_TDM_SYSTEM_LB_EN_W (1)
#define WUFEI_TDM_SYSTEM_LB_EN_F(v) WUFEI_FIELD(v, WUFEI_TDM_SYSTEM_LB_EN_S)
#define WUFEI_TDM_SYSTEM_LB_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_SYSTEM_LB_EN_S, WUFEI_TDM_SYSTEM_LB_EN_W)
#define WUFEI_TDM_SYSTEM_LB_EN_M \
        WUFEI_MASK(WUFEI_TDM_SYSTEM_LB_EN_S, WUFEI_TDM_SYSTEM_LB_EN_W)

#define WUFEI_TDM_SYSTEM_LB_UNFRM_S (1)
#define WUFEI_TDM_SYSTEM_LB_UNFRM_W (1)
#define WUFEI_TDM_SYSTEM_LB_UNFRM_F(v) WUFEI_FIELD(v, WUFEI_TDM_SYSTEM_LB_UNFRM_S)
#define WUFEI_TDM_SYSTEM_LB_UNFRM_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_SYSTEM_LB_UNFRM_S, WUFEI_TDM_SYSTEM_LB_UNFRM_W)
#define WUFEI_TDM_SYSTEM_LB_UNFRM_M \
        WUFEI_MASK(WUFEI_TDM_SYSTEM_LB_UNFRM_S, WUFEI_TDM_SYSTEM_LB_UNFRM_W)

#define WUFEI_TDM_SYSTEM_LB_E1_T1_S (2)
#define WUFEI_TDM_SYSTEM_LB_E1_T1_W (1)
#define WUFEI_TDM_SYSTEM_LB_E1_T1_F(v) WUFEI_FIELD(v, WUFEI_TDM_SYSTEM_LB_E1_T1_S)
#define WUFEI_TDM_SYSTEM_LB_E1_T1_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_SYSTEM_LB_E1_T1_S, WUFEI_TDM_SYSTEM_LB_E1_T1_W)
#define WUFEI_TDM_SYSTEM_LB_E1_T1_M \
        WUFEI_MASK(WUFEI_TDM_SYSTEM_LB_E1_T1_S, WUFEI_TDM_SYSTEM_LB_E1_T1_W)

#define WUFEI_TDM_SYSTEM_LB_CAS_S (3)
#define WUFEI_TDM_SYSTEM_LB_CAS_W (1)
#define WUFEI_TDM_SYSTEM_LB_CAS_F(v) WUFEI_FIELD(v, WUFEI_TDM_SYSTEM_LB_CAS_S)
#define WUFEI_TDM_SYSTEM_LB_CAS_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_SYSTEM_LB_CAS_S, WUFEI_TDM_SYSTEM_LB_CAS_W)
#define WUFEI_TDM_SYSTEM_LB_CAS_M \
        WUFEI_MASK(WUFEI_TDM_SYSTEM_LB_CAS_S, WUFEI_TDM_SYSTEM_LB_CAS_W)

#define WUFEI_TDM_SYSTEM_LB_VC3_S (4)
#define WUFEI_TDM_SYSTEM_LB_VC3_W (1)
#define WUFEI_TDM_SYSTEM_LB_VC3_F(v) WUFEI_FIELD(v, WUFEI_TDM_SYSTEM_LB_VC3_S)
#define WUFEI_TDM_SYSTEM_LB_VC3_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_SYSTEM_LB_VC3_S, WUFEI_TDM_SYSTEM_LB_VC3_W)
#define WUFEI_TDM_SYSTEM_LB_VC3_M \
        WUFEI_MASK(WUFEI_TDM_SYSTEM_LB_VC3_S, WUFEI_TDM_SYSTEM_LB_VC3_W)

#define WUFEI_TDM_SYSTEM_LB_OC3_S (5)
#define WUFEI_TDM_SYSTEM_LB_OC3_W (1)
#define WUFEI_TDM_SYSTEM_LB_OC3_F(v) WUFEI_FIELD(v, WUFEI_TDM_SYSTEM_LB_OC3_S)
#define WUFEI_TDM_SYSTEM_LB_OC3_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_SYSTEM_LB_OC3_S, WUFEI_TDM_SYSTEM_LB_OC3_W)
#define WUFEI_TDM_SYSTEM_LB_OC3_M \
        WUFEI_MASK(WUFEI_TDM_SYSTEM_LB_OC3_S, WUFEI_TDM_SYSTEM_LB_OC3_W)

#define WUFEI_TDM_SYSTEM_LB_OC12_S (6)
#define WUFEI_TDM_SYSTEM_LB_OC12_W (1)
#define WUFEI_TDM_SYSTEM_LB_OC12_F(v) WUFEI_FIELD(v, WUFEI_TDM_SYSTEM_LB_OC12_S)
#define WUFEI_TDM_SYSTEM_LB_OC12_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_SYSTEM_LB_OC12_S, WUFEI_TDM_SYSTEM_LB_OC12_W)
#define WUFEI_TDM_SYSTEM_LB_OC12_M \
        WUFEI_MASK(WUFEI_TDM_SYSTEM_LB_OC12_S, WUFEI_TDM_SYSTEM_LB_OC12_W)

#define WUFEI_TDM_IDLE_DATA_PATTERN_S (0)
#define WUFEI_TDM_IDLE_DATA_PATTERN_W (8)
#define WUFEI_TDM_IDLE_DATA_PATTERN_F(v) WUFEI_FIELD(v, WUFEI_TDM_IDLE_DATA_PATTERN_S)
#define WUFEI_TDM_IDLE_DATA_PATTERN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_IDLE_DATA_PATTERN_S, WUFEI_TDM_IDLE_DATA_PATTERN_W)
#define WUFEI_TDM_IDLE_DATA_PATTERN_M \
        WUFEI_MASK(WUFEI_TDM_IDLE_DATA_PATTERN_S, WUFEI_TDM_IDLE_DATA_PATTERN_W)

#define WUFEI_TDM_IDLE_CAS_PATTERN_S (8)
#define WUFEI_TDM_IDLE_CAS_PATTERN_W (4)
#define WUFEI_TDM_IDLE_CAS_PATTERN_F(v) WUFEI_FIELD(v, WUFEI_TDM_IDLE_CAS_PATTERN_S)
#define WUFEI_TDM_IDLE_CAS_PATTERN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_IDLE_CAS_PATTERN_S, WUFEI_TDM_IDLE_CAS_PATTERN_W)
#define WUFEI_TDM_IDLE_CAS_PATTERN_M \
        WUFEI_MASK(WUFEI_TDM_IDLE_CAS_PATTERN_S, WUFEI_TDM_IDLE_CAS_PATTERN_W)

#define WUFEI_TDM_ENTRY_ACTIVE_S (12)
#define WUFEI_TDM_ENTRY_ACTIVE_W (1)
#define WUFEI_TDM_ENTRY_ACTIVE_F(v) WUFEI_FIELD(v, WUFEI_TDM_ENTRY_ACTIVE_S)
#define WUFEI_TDM_ENTRY_ACTIVE_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_ENTRY_ACTIVE_S, WUFEI_TDM_ENTRY_ACTIVE_W)
#define WUFEI_TDM_ENTRY_ACTIVE_M \
        WUFEI_MASK(WUFEI_TDM_ENTRY_ACTIVE_S, WUFEI_TDM_ENTRY_ACTIVE_W)

#define WUFEI_TDM_ENTRY_PHY_ID_S (0)
#define WUFEI_TDM_ENTRY_PHY_ID_W (13)
#define WUFEI_TDM_ENTRY_PHY_ID_F(v) WUFEI_FIELD(v, WUFEI_TDM_ENTRY_PHY_ID_S)
#define WUFEI_TDM_ENTRY_PHY_ID_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_ENTRY_PHY_ID_S, WUFEI_TDM_ENTRY_PHY_ID_W)
#define WUFEI_TDM_ENTRY_PHY_ID_M \
        WUFEI_MASK(WUFEI_TDM_ENTRY_PHY_ID_S, WUFEI_TDM_ENTRY_PHY_ID_W)

#define WUFEI_TDM_ENTRY_FIRST_S (11)
#define WUFEI_TDM_ENTRY_FIRST_W (1)
#define WUFEI_TDM_ENTRY_FIRST_F(v) WUFEI_FIELD(v, WUFEI_TDM_ENTRY_FIRST_S)
#define WUFEI_TDM_ENTRY_FIRST_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_ENTRY_FIRST_S, WUFEI_TDM_ENTRY_FIRST_W)
#define WUFEI_TDM_ENTRY_FIRST_M \
        WUFEI_MASK(WUFEI_TDM_ENTRY_FIRST_S, WUFEI_TDM_ENTRY_FIRST_W)

#define WUFEI_TDM_MODE_RAM_LINE_MODE_S (0)
#define WUFEI_TDM_MODE_RAM_LINE_MODE_W (2)
#define WUFEI_TDM_MODE_RAM_LINE_MODE_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_RAM_LINE_MODE_S)
#define WUFEI_TDM_MODE_RAM_LINE_MODE_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_RAM_LINE_MODE_S, WUFEI_TDM_MODE_RAM_LINE_MODE_W)
#define WUFEI_TDM_MODE_RAM_LINE_MODE_M \
        WUFEI_MASK(WUFEI_TDM_MODE_RAM_LINE_MODE_S, WUFEI_TDM_MODE_RAM_LINE_MODE_W)


#define WUFEI_TDM_MODE_RAM_PDH_SYS_LB_EN_S (2)
#define WUFEI_TDM_MODE_RAM_PDH_SYS_LB_EN_W (1)
#define WUFEI_TDM_MODE_RAM_PDH_SYS_LB_EN_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_RAM_PDH_SYS_LB_EN_S)
#define WUFEI_TDM_MODE_RAM_PDH_SYS_LB_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_RAM_PDH_SYS_LB_EN_S, WUFEI_TDM_MODE_RAM_PDH_SYS_LB_EN_W)
#define WUFEI_TDM_MODE_RAM_PDH_SYS_LB_EN_M \
        WUFEI_MASK(WUFEI_TDM_MODE_RAM_PDH_SYS_LB_EN_S, WUFEI_TDM_MODE_RAM_PDH_SYS_LB_EN_W)


#define WUFEI_TDM_MODE_RAM_PDH_LINE_LB_EN_S (3)
#define WUFEI_TDM_MODE_RAM_PDH_LINE_LB_EN_W (1)
#define WUFEI_TDM_MODE_RAM_PDH_LINE_LB_EN_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_RAM_PDH_LINE_LB_EN_S)
#define WUFEI_TDM_MODE_RAM_PDH_LINE_LB_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_RAM_PDH_LINE_LB_EN_S, WUFEI_TDM_MODE_RAM_PDH_LINE_LB_EN_W)
#define WUFEI_TDM_MODE_RAM_PDH_LINE_LB_EN_M \
        WUFEI_MASK(WUFEI_TDM_MODE_RAM_PDH_LINE_LB_EN_S, WUFEI_TDM_MODE_RAM_PDH_LINE_LB_EN_W)


#define WUFEI_TDM_MODE_RAM_PDH_INDEX_S (4)
#define WUFEI_TDM_MODE_RAM_PDH_INDEX_W (4)
#define WUFEI_TDM_MODE_RAM_PDH_INDEX_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_RAM_PDH_INDEX_S)
#define WUFEI_TDM_MODE_RAM_PDH_INDEX_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_RAM_PDH_INDEX_S, WUFEI_TDM_MODE_RAM_PDH_INDEX_W)
#define WUFEI_TDM_MODE_RAM_PDH_INDEX_M \
        WUFEI_MASK(WUFEI_TDM_MODE_RAM_PDH_INDEX_S, WUFEI_TDM_MODE_RAM_PDH_INDEX_W)


#define WUFEI_TDM_MODE_RAM_CC_INDEX_S (8)
#define WUFEI_TDM_MODE_RAM_CC_INDEX_W (4)
#define WUFEI_TDM_MODE_RAM_CC_INDEX_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_RAM_CC_INDEX_S)
#define WUFEI_TDM_MODE_RAM_CC_INDEX_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_RAM_CC_INDEX_S, WUFEI_TDM_MODE_RAM_CC_INDEX_W)
#define WUFEI_TDM_MODE_RAM_CC_INDEX_M \
        WUFEI_MASK(WUFEI_TDM_MODE_RAM_CC_INDEX_S, WUFEI_TDM_MODE_RAM_CC_INDEX_W)


#define WUFEI_TDM_MODE_RX_EN_S (0)
#define WUFEI_TDM_MODE_RX_EN_W (1)
#define WUFEI_TDM_MODE_RX_EN_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_RX_EN_S)
#define WUFEI_TDM_MODE_RX_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_RX_EN_S, WUFEI_TDM_MODE_RX_EN_W)
#define WUFEI_TDM_MODE_RX_EN_M \
        WUFEI_MASK(WUFEI_TDM_MODE_RX_EN_S, WUFEI_TDM_MODE_RX_EN_W)

#define WUFEI_TDM_MODE_RX_PARITY_S (1)
#define WUFEI_TDM_MODE_RX_PARITY_W (1)
#define WUFEI_TDM_MODE_RX_PARITY_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_RX_PARITY_S)
#define WUFEI_TDM_MODE_RX_PARITY_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_RX_PARITY_S, WUFEI_TDM_MODE_RX_PARITY_W)
#define WUFEI_TDM_MODE_RX_PARITY_M \
        WUFEI_MASK(WUFEI_TDM_MODE_RX_PARITY_S, WUFEI_TDM_MODE_RX_PARITY_W)

#define WUFEI_TDM_MODE_TX_EN_S (8)
#define WUFEI_TDM_MODE_TX_EN_W (1)
#define WUFEI_TDM_MODE_TX_EN_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_TX_EN_S)
#define WUFEI_TDM_MODE_TX_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_TX_EN_S, WUFEI_TDM_MODE_TX_EN_W)
#define WUFEI_TDM_MODE_TX_EN_M \
        WUFEI_MASK(WUFEI_TDM_MODE_TX_EN_S, WUFEI_TDM_MODE_TX_EN_W)

#define WUFEI_TDM_MODE_TX_PARITY_S (9)
#define WUFEI_TDM_MODE_TX_PARITY_W (1)
#define WUFEI_TDM_MODE_TX_PARITY_F(v) WUFEI_FIELD(v, WUFEI_TDM_MODE_TX_PARITY_S)
#define WUFEI_TDM_MODE_TX_PARITY_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_MODE_TX_PARITY_S, WUFEI_TDM_MODE_TX_PARITY_W)
#define WUFEI_TDM_MODE_TX_PARITY_M \
        WUFEI_MASK(WUFEI_TDM_MODE_TX_PARITY_S, WUFEI_TDM_MODE_TX_PARITY_W)

#define WUFEI_TDM_SYS_LB_EN_S (0)
#define WUFEI_TDM_SYS_LB_EN_W (1)
#define WUFEI_TDM_SYS_LB_EN_F(v) WUFEI_FIELD(v, WUFEI_TDM_SYS_LB_EN_S)
#define WUFEI_TDM_SYS_LB_EN_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_SYS_LB_EN_S, WUFEI_TDM_SYS_LB_EN_W)
#define WUFEI_TDM_SYS_LB_EN_M \
        WUFEI_MASK(WUFEI_TDM_SYS_LB_EN_S, WUFEI_TDM_SYS_LB_EN_W)

#define WUFEI_TDM_SYS_LB_UNFRM_S (1)
#define WUFEI_TDM_SYS_LB_UNFRM_W (1)
#define WUFEI_TDM_SYS_LB_UNFRM_F(v) WUFEI_FIELD(v, WUFEI_TDM_SYS_LB_UNFRM_S)
#define WUFEI_TDM_SYS_LB_UNFRM_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_SYS_LB_UNFRM_S, WUFEI_TDM_SYS_LB_UNFRM_W)
#define WUFEI_TDM_SYS_LB_UNFRM_M \
        WUFEI_MASK(WUFEI_TDM_SYS_LB_UNFRM_S, WUFEI_TDM_SYS_LB_UNFRM_W)

#define WUFEI_TDM_SYS_LB_E1_T1N_S (2)
#define WUFEI_TDM_SYS_LB_E1_T1N_W (1)
#define WUFEI_TDM_SYS_LB_E1_T1N_F(v) WUFEI_FIELD(v, WUFEI_TDM_SYS_LB_E1_T1N_S)
#define WUFEI_TDM_SYS_LB_E1_T1N_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_SYS_LB_E1_T1N_S, WUFEI_TDM_SYS_LB_E1_T1N_W)
#define WUFEI_TDM_SYS_LB_E1_T1N_M \
        WUFEI_MASK(WUFEI_TDM_SYS_LB_E1_T1N_S, WUFEI_TDM_SYS_LB_E1_T1N_W)

#define WUFEI_TDM_SYS_LB_MF_MODE_S (3)
#define WUFEI_TDM_SYS_LB_MF_MODE_W (1)
#define WUFEI_TDM_SYS_LB_MF_MODE_F(v) WUFEI_FIELD(v, WUFEI_TDM_SYS_LB_MF_MODE_S)
#define WUFEI_TDM_SYS_LB_MF_MODE_V(f) \
        WUFEI_VALUE(f, WUFEI_TDM_SYS_LB_MF_MODE_S, WUFEI_TDM_SYS_LB_MF_MODE_W)
#define WUFEI_TDM_SYS_LB_MF_MODE_M \
        WUFEI_MASK(WUFEI_TDM_SYS_LB_MF_MODE_S, WUFEI_TDM_SYS_LB_MF_MODE_W)

#define WUFEI_hw_tdm_entry   WP_U16

#endif /* WUFEI_HW_TDM_H*/
