#ifndef __FIBERHOME_H__
#define __FIBERHOME_H__

#define MORRIS_DISABLE_PORT_MODIFY	(0)
#define MORRIS_CHANGE_INTERFACE_TYPE	(1)
#define MORRIS_AUTO_START		(1)
#define MORRIS_DISABLE_ENABLE_PORT	(1)

#endif
